### ISSUE TITLE
コマンドラインでの挙動

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#1]
申し訳ありません。別のところに書き込んでしまいましたが、ここでよろしいのでしょうか？

AttacheCase 2.8.2.8 は大変有用につかわさせて頂いております。
新しくなった AttacheCase 3.0.1.0 も入れてみましたが、以下のような現象に見舞われています。
いずれも従来のバージョンでは見られない現象です。
ご確認をよろしくお願いいたします。

1. AttacheCase #3 で暗号化する場合
  AttacheCase.exe /exit=1 /ow=0 /withext=1 [path]abc.txt
としたとき、2回目のパスワード入力より表示される。
しかも入力フォーカスが？

2. 復号化する場合
  AttacheCase.exe /exit=1 /ow=0 /opf=1 [path]abc.txt.atc
としたとき、復号化はできるがテキストファイルが開けない → 例外エラーになる。
”オブジェクト参照がオブジェクト インスタンスに設定されていません。”

3．オプションの「暗号化ファイル名に拡張子を含める」のチェックが保持されない。

**Comment by hibara** [comment]
ご報告ありがとうございます！（こちらで問題ありません）
「1」「2」「3」のいずれの問題も原因が判明しましたので（コマンドライン周りはずたぼろでしたね・・・）、すべて修正して以下、バージョンアップいたしました。よろしくご確認のほど、お願いいたします。

https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
Ver.3.0.1.2 にて修正されているのを確認いたしました。
早速の対応ありがとうございます。
