### ISSUE TITLE
コマンドラインオプション /del ?

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#10]
Ver.3.0.1.9 にてチェックしました。
AttacheCase.exe /exit=1 /ow=0 /en=1 /withext=1 /del=1 [path]abc.txt

以下のように動作が設定とは異なるようです。
0: 削除しない → 完全削除
1: 通常削除 → ごみ箱への削除
2: 完全削除 → Ok
3: ごみ箱への削除 → 削除しない

勿論、コマンドラインよりでなければ（0 相当）削除されることはありません。
ご確認ください。

**Comment by hibara** [comment]
ご報告ありがとうございます！

仰るとおり、コマンドラインオプションの設定が間違っておりました。。。また、処理順も本体と異なっており、正解は以下の順の通りでした。

  0:削除しない, 
  1:通常，
  2:ごみ箱への削除，
  3:完全削除

また、完全削除も正しく動作しなかった問題に対処した新バージョンを公開しました。
もしよろしければお試しください。↓

ver.3.0.2.0
https://hibara.org/software/attachecase/

では今後ともよろしくお願いいたします。

**Comment by yukicon** [comment]
Ver.3.0.2.1 にて /del=0～3 の動作が正常であることを確認しました。
