### ISSUE TITLE
/list=[path]List.txt の文字コード

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#11]
AttacheCase.exe /exit=1 /ow=0 /en=1 /oneby=1 /withext=1 /del=1 /list=[path]List.txt

1. List.txt が ＳＪＩＳ コードだとリスト中の1個が暗号化されない。（3個のファイルで行った）
    ＵＴＦ－８ では問題ない。
2． /del=1 が指定されているのに削除されない

Ｖｅｒ．3.1.0.2 にて確認いたしました。

**Comment by yukicon** [comment]
発生条件を追加いたします。
List.txt の中身が
  s021.txt
  山田.txt
  s02s.txt

とすると、山田.txt のみ暗号化できない。
順序に関係ありません。

**Comment by hibara** [comment]
ご報告ありがとうございます！

たしかに文字コードの問題で正常に動作していなかったようです。自動判別して読み込むようにしました。ただ、完全には無理なので、UTF-8のBOM付きなどにした方が無難かと思います。

なお、じゃっかん/listの動作が変わって、一つにまとめて暗号化することに仕様を変更しました。今まで通り個別で行いたい場合は、/oneby=1を付けてください。

ver.3.1.0.3
https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
ver.3.1.0.3 にて確認しましたが、SJIS コードだとリスト中の日本語ファイル名のモノが暗号化されないのに変わりありませんでした。
しかし確認したところ、ver.2.8.2.8 でも UTF-8、UTF-16 で問題ありませんので文字コードは（勝手に）仕様変更と言うことで了承いたします。
将来的にもその方向だと思いますし。

尚、最初に書きましたように、/oneby=1 は指定しています。
AttacheCase.exe /exit=1 /ow=0 /en=1 /oneby=1 /withext=1 /del=1 /list=[path]List.txt

もう一つの不具合（ver.2.8.2.8 と変わってしまった？）の上記のごとく /del=1 を指定しているのにもかかわらず削除されない点も変化有りません。

**Comment by hibara** [comment]
/del=1 のオプションが効かない点ですが、別件の問題に対処した際に、解消されたようです。よろしければ最新版でお試しください。↓

ver.3.1.0.6
https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
/del=1 の不具合が解消されたことを確認いたしました。
ありがとうございます。
