### ISSUE TITLE
WindowsXPでの動作について

### ISSUE THREAD

**Issue by HappyTCL** [hibara/AttacheCase3#12]
いつもお世話になっております。
アタッシェケースVer3を使用してみたのですが、以下の条件でエラーメッセージが出ます。

【使用環境】
OS：WindowsXP sp3
　　※クローズドネットワークで使用しているため、WindowsUpdateも長らくしてません
　　※ .NET Framework4インストール済み

【確認したこと】
暗号化→
　(1)エラーがでて暗号化できない

複合化→
　(2)別のPC（Win7）のアタッシェケースVer3で作成した「txt」の暗号化（atc）ファイル：複合化できた
　(3)別のPC（Win7）のアタッシェケースVer3で作成した「xls」の暗号化（atc）ファイル：複合化できたけどエラーもでる

(3)実行時には、80～90％くらいで、「The specified cryptographic algorithm is not supported on this platform.」というメッセージが出ます。
そのあと、「エラー」というウインドウに「予期せぬエラーが発生しました。処理を中止します。」というメッセージが表示されて、完了していないはずですが、デスクトップには複合化したファイルがあります。
これはエラーは出るけど複合化はできているということでしょうか？

また、使用しているWindowsXPに何かOSのセキュリティパッチが足りなくて出る現象なのでしょうか？
『WindowsXPで「一応」動きます』と書かれていた「一応」の部分は上記範囲でしょうか？

ノーサポートのところおそれいりますが、現在行き詰っておりますので、何かご助言いただけますと幸いです…！

**Comment by hibara** [comment]
ご報告ありがとうございます！

WindowsXPでも「一応」動きますと書いたのは、.NET Framework 4がギリギリ動くOSだったからです。開発当初は試したりもしていたのですが、いつの頃からか、WindowsXP環境をバラしてしまいまして・・・

いま再構築しておりますので、お時間をいただくかもしれません。調査・検証まで今しばらくお待ちください。

**Comment by HappyTCL** [comment]
再構築のご対応いただきありがとうございます！
ちなみに、どのくらい時間がかかりそうかだいたいの目安でかまいませんので教えていただいてもよろしいでしょうか？
よろしくお願いいたします。

**Comment by hibara** [comment]
お時間をだいぶいただいて申し訳ありません。環境構築に戸惑ってました（三回も再インストールしてしまいました）。

Windows XPで正常に動作しなかった問題について対処したバージョンを以下に公開しました。

ver.3.1.0.4
https://hibara.org/software/attachecase/

よろしければお試しください。

**Comment by HappyTCL** [comment]
こんにちは、HappyTCLです。
こちらでも動作に問題がないことを確認いたしました。
サポートの切れているOSでの動作検証のため、環境構築などお手数をおかけいたしました。
このたびはご対応いただき、まことにありがとうございました！
