### ISSUE TITLE
 アタッシェケース#3　ver.3.1.0.2で、複数ファイルの暗号化ができない

### ISSUE THREAD

**Issue by un-nondry** [hibara/AttacheCase3#13]
複数ファイルをドラッグ&ドロップして暗号化をスタートすると下記のようなエラーウィンドウが表示されて下記のエラー内容と「詳細」、「続行」、「終了」ボタンが表示されます。
対応よろしくお願いいたします。

[動作環境]
Windows10Home
.NET Framework 4は.NET Framework 4インストーラーにてインストール済を確認

下記がエラーメッセージの詳細です。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
アプリケーションのコンポーネントで、ハンドルされていない例外が発生しました。[続行]をクリックすると、アプリケーションは直ちに終了します。
別のプロセスで使用せれているためプロセスファイル 'E\ac\xxxxx.atc' にアクセスできません。

＜詳　細＞
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.IO.IOException: 別のプロセスで使用されているため、プロセスはファイル 'E:\ac\xxxxx.atc' にアクセスできません。
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 Microsoft.VisualBasic.FileIO.FileSystem.DeleteFileInternal(String file, UIOptionInternal showUI, RecycleOption recycle, UICancelOption onUserCancel)
   場所 AttacheCase.Form1.backgroundWorker_Encryption_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   場所 System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** 読み込まれたアセンブリ **************
mscorlib
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1080.0 built by: NETFXREL3STAGE
    コードベース:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AttacheCase
    アセンブリ バージョン:3.1.0.2
    Win32 バージョン:3.1.0.2
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase3/AttacheCase.exe
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1038.0 built by: NETFXREL2
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1081.0 built by: NETFXREL3STAGE
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1078.0 built by: NETFXREL3STAGE
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1038.0 built by: NETFXREL2
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1084.0 built by: NETFXREL3STAGE
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1064.2 built by: NETFXREL3STAGE
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AttacheCase.resources
    アセンブリ バージョン:3.1.0.2
    Win32 バージョン:3.1.0.2
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase3/ja-JP/AttacheCase.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1055.0 built by: NETFXREL2
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    アセンブリ バージョン:1.1.0.0
    Win32 バージョン:1.1.0.0
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase3/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    アセンブリ バージョン:1.1.0.0
    Win32 バージョン:1.1.0.0
    コードベース:file:///C:/Program%20Files%20(x86)/AttacheCase3/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
mscorlib.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.6.1055.0 built by: NETFXREL2
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.VisualBasic
    アセンブリ バージョン:10.0.0.0
    Win32 バージョン:14.6.1055.0 built by: NETFXREL2
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------

************** JIT デバッグ **************
Just-In-Time (JIT) デバッグを有効にするには、このアプリケーション、
またはコンピューター (machine.config) の構成ファイルの jitDebugging 
値を system.windows.forms セクションで設定しなければなりません。
アプリケーションはまた、デバッグを有効にしてコンパイルされなければ
なりません。

例:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT デバッグが有効なときは、このダイアログ ボックスで処理するよりも、
ハンドルされていない例外はすべてコンピューターに登録された
JIT デバッガーに設定されなければなりません。

**Comment by hibara** [comment]
ご報告ありがとうございます！
その不具合は、別件で調査中のところ発見いたしまして、ちょうど今日更新をかけるところでした。

以下のバージョンで対処が入っているはずです。
ver.3.1.0.3
https://hibara.org/software/attachecase/

よろしければお試し下さい。

**Comment by un-nondry** [comment]
早速の対応ありがとうございます。
エラー出ずに暗号化できました。

ただ、動作設定で[保存->暗号化->複数ファイルの場合]で「通常」を選択して複数のファイルを暗号化すると
一つのファイルにまとめられてしまうのです。
Vre2のとき「何もしない」がVre3の「通常」と文言が変わったものと思っていたのですが違うのでしょうか？

**Comment by hibara** [comment]
ご報告ありがとうございます！

その辺り修正を入れて以下にアップデートを公開いたしました。↓
ver.3.1.0.5
https://hibara.org/software/attachecase/

おそらく期待通りの動きになっているとは思います。
ではよろしくお願いいたします。

**Comment by un-nondry** [comment]
修正ありがとうございます。

通常を選択した場合の動作がVer２のときと同じになり使いやすくなりました。
ありがとうございます。
