### ISSUE TITLE
アタッシェケース#3　ver.3.1.0.2で、拡張子偽装が機能しない

### ISSUE THREAD

**Issue by un-nondry** [hibara/AttacheCase3#14]
動作設定で「暗号化ファイルの拡張子偽装（ピリオドを含む）にチェックを入れても「適用->OK」ボタンを
クリックして動作設定画面を閉じて再度設定を見るとチェックが外れて機能しません。
暗号化してもデフォルトの拡張子「atc」になっています。

対応よろしくお願いいたします。

**Comment by hibara** [comment]
こちらもご報告ありがとうございます！
これは凡ミスで、設定が正しく保存されていなかったようです。

こちらも以下の最新バージョンで修正済みです。
ver.3.1.0.3
https://hibara.org/software/attachecase/

では今後ともよろしくお願いいたします。

**Comment by un-nondry** [comment]
早速の対応ありがとうございます。
問題なく動作しました。
