### ISSUE TITLE
日本語名のファイルを暗号ZIP化すると文字化けする

### ISSUE THREAD

**Issue by pmakino** [hibara/AttacheCase3#17]
アタッシェケース 3.1.0.3 の「パスワードZIP」にて、日本語を含む名前のファイルを暗号化したところ、
当該ZIPファイルをWindows標準の圧縮フォルダーで開いたところ、「このフォルダーは空です。」と、ファイルが存在しないものとして扱われました。
また、Explzhで開いてみたところ、ファイル名のうち日本語の部分が?と文字化けしていました。

改善いただけると幸いです。
よろしくお願いいたします。

**Comment by hibara** [comment]
ご報告ありがとうございます！

まったくもって典型的なバグを入れてしまいました。。。日本語名を含むファイルをパスワード付きZIP圧縮しても文字化けしないように改良しました。具体的には文字コードをShift-JISとしました。

以下にその対処を入れた最新版をアップロードしました。よろしければお試しください。

ver.3.1.0.7
https://hibara.org/software/attachecase/

**Comment by pmakino** [comment]
3.1.0.7で改善されていることを確認できました。
ありがとうございました。
