### ISSUE TITLE
古いファイルが復号化できないなど

### ISSUE THREAD

**Issue by ghost** [hibara/AttacheCase3#2]
1．AttacheCase 3.0.1.2 にて古いファイルが復号化できない。
実際には終了するのに復号化されたファイルが無い（出力されていない）
以下のタイムスタンプより Attche Case 2.7.5.0 を使っているようです。
-------------------
非実行ファイル

Alternate Data Stream

作成日時		：2012/12/19 17:30"04
更新日時		：2012/12/19 17:30"04
アクセス日時	：2012/12/19 17:30"04

サイズ		：5,248バイト(5.13KB)
ファイル属性	：A

フルパス：[path]abc.txt.atc

バージョン情報は存在しません
-------------------
勿論、Ver.2.8.2.8 では問題ありません。
また、殆どのあるいは今行った Ver.2.8.2.8 で暗号化したファイルは Ver.3.0.1.2 で復号化されます。

2．/list=List.txt にてエラーとなる
コマンドラインから複数ファイルの暗号化を行った場合、
List.txt
a.txt
b.txt
c.txt

AttacheCase.exe /exit=1 /ow=0 /en=1 /withext=1 /list=[path]List.txt

-------------------
注意
保存先のフォルダーが見つかりません！　処理を中止します。
-------------------

**Comment by hibara** [comment]
ご報告ありがとうございます！

ご指摘の通り、ver.2.8.0.0以前に暗号化されたファイルには、Shift-JISのファイル名しか格納しておらず（それ以降はUnicodeと共存）、おそらくそこでファイルが開かなくなっているのだと思います。

また、コマンドラインオプションの「/list」も直してみました。

それぞれ、最新版でお試し下さい。

https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
Ver.2.7.5.0  で暗号化されたファイルが復号化できることを確認いたしました。
しかし、Ver.3.0.1.0 で暗号化したファイルが復号化できなくなりました。以下のところで止まります。
復号するための準備をしています...
- %

コマンドラインオプションの「/list」ですが、現象が変わりません。
リストファイルの文字コードが「UTF-8 BOM無」ですが、「S-JIS」でないとだめでしょうか？
このコードでは今使っているエディターでは保存できません。

**Comment by hibara** [comment]
> Ver.3.0.1.0 で暗号化したファイルが復号化できなくなりました。

取り急ぎこの問題には対処しました。ver.3.0.1.3まで機能していなかった圧縮設定を入れた影響と思われます。

ver.3.0.1.4
https://hibara.org/software/attachecase/

「/list」は、UTF-8でテストしたはずなんですが・・・すみません、こちらはしばらくお時間をください。優先度の高いバグ報告が続々と来ているため(泣)、その隙間でやります。

**Comment by yukicon** [comment]
Ver.3.0.1.5 にて /list は動きましたが、Ver.2.8.2.8 とは挙動が違います。

AttacheCase.exe /exit=1 /ow=0 /en=1 /withext=1 /list=[path]List.txt
List.txt
a.txt
b.txt
c.txt

Ver.2.8.2.8 のとき a.txt.atc b.txt.atc c.txt.atc が生成される
Ver.3.0.1.5 のとき c.txt.atc のみが生成される → 復号化すると、a.txt b.txt c.txt が生成される
即ち、アーカイブされた形になっている。

仕様が変わったと理解してよろしいでしょうか?

**Comment by hibara** [comment]
ちょっと修正を悩んだのですが、従来の仕様ではなく、現状のまとめてアーカイブされる仕様のままで行こうかと思います。

とはいえ、個別に暗号化できないのも困りますので、上記オプションにて、「/oneby=1」を追加して実行してみてください。期待通りの動きになるかと思います。この仕様は、新バージョンで入れましたので、以下からダウンロード、お試しください。

ver.3.0.1.6
https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
アーカイブされる仕様は良さそうですね。

しかし、Ver.3.0.1.6 は暗号化も復号化もできなくなりました。
パスワードが入力できません。

**Comment by hibara** [comment]
いつもご報告ありがとうございます！

これは大変お恥ずかしいミスをしてしまいました・・・。毎回、ビルド後は一連のテストはしているのですが、パスワード未入力（空白）での軽いテストしてしまうことが多く、この凡ミスを見逃しました・・・以後、テスト手順を変えて、再発防止に努めます。

急遽修正して、
ver.3.0.1.7
https://hibara.org/software/attachecase/

にて対処しました。
よろしくお願いいたします。

**Comment by yukicon** [comment]
素早い対応ですね。確認いたしました。

個別圧縮の /oneby=1 を使ってみました。
AttacheCase.exe /exit=1 /ow=0 /en=1 /oneby=1 /withext=1 /list=[path]List.txt
結果は OK なのですが、

暗号化しています...
100.00%
キャンセル(&C)

と自動的に閉じてくれません。

**Comment by hibara** [comment]
これはたいへん失礼しました。。。個別の暗号化は他とは別の処理の流れになっているため、終了後の処理がごっそり行われておりませんでした（削除処理、終了処理など）。

その問題に対処したものを以下にアップロードいたしました。よろしければお試しください。

ver.3.0.1.8
https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
/oneby=1 or 0 の動作を確認しました。

私の使用している状態や、これまでの課題を再度チェックして問題はありませんでした。
Ver.3 に切り替えて行こうと思います。
ありがとうございました。
