### ISSUE TITLE
コマンドラインオプション /ow の動作が逆になった？

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#27]
最新版 Ver.3.1.1.3 で /ow の動作が逆になったのですが、定義が変わりましたか?

/ow=0 上書きを確認する
/ow=1 上書きを確認しない（許可する）

のように従来は動作していたのですが、いつの間にか逆になってしまいました?

**Comment by hibara** [comment]
ご報告ありがとうございます！

申し訳ありません。こちら、仰るとおり定義が変わりました。
実際、動作設定では「上書きの確認する＝ON」となっていたため、それらに合わせた形になっております。

ヘルプファイルの方にも昔の記述が残っておりましたので、修正しました。

ではよろしくお願いいたします。

**Comment by yukicon** [comment]
了解しました。
ヘルプファイルの方も確認いたしました。
