### ISSUE TITLE
復号時のエラーについて

### ISSUE THREAD

**Issue by momobudou** [hibara/AttacheCase3#28]
前バージョンから長らくお世話なっております。

暗号化ファイルのタイプatcで復号時
エラー　パスワードがちがうか、ファイルが破損している可能性があります。復号化できませんでした。
となりok後復号化パスワード入力作業となります。

暗号化時のパスワード保存：設定しております。
複合時のパスワード保存：設定しておりませんが何故か空欄にはなりません。
暗号/復号時に確認無しに記憶パスワードで実行する：チェック入れております。
としています。

お問い合わせをずっと覗いておりますがどなたも指摘がないので個人的な環境の問題でしょうか？
お手数ですがご確認お願い致します。

**Comment by hibara** [comment]
ご報告ありがとうございます！

こちらのバグ、再現いたしました。。。なぜ今まで残っていたのか・・・。

それら、修正したものを公開しました。↓

ver.3.2.0.0
https://hibara.org/software/attachecase/

よろしければこちらでお試しください。
ではよろしくお願いいたします。

**Comment by momobudou** [comment]
対応ありがとうございました。

これからも使用させていただきます。
よろしくお願いいたします。
