### ISSUE TITLE
パスワードがらみで、変な動きがあります

### ISSUE THREAD

**Issue by akibataro** [hibara/AttacheCase3#29]
お世話になります
パスワードがらみで、以下の３つを気づきました。。

「環境」
windows10 anniversary pro 64bit
atcs3113.zip AttacheCase.exe　←アタッシェケース#3　ver.3.1.1.3 - 2016/10/28 

１）パスワードの桁数
■ただし、パスワードの入力文字数には制限があり、
■大文字小文字を区別し、半角で32文字（全角だと16文字）以内です

半角　５０桁　OK
倍角　３０桁　OK

多い分には構わないと思います。。制限を超えても

２）「パスワード入力」ができない
一旦パスワードファイルを使うと

もう「パスワード入力」ができない

本人は「パスワードファイル入力」で頭がいっぱいになるので

「対処」
AttacheCase.exe
↓　一旦終了

再度　AttacheCase.exe　実行
↓
直ります　←パスワード入力　を思い出す！

３）パスワードファイル入力で「復号化」エラー

「暗号化」OK
「パスワードファイルのドラッグ＆ドロップを許可する」
↓
暗号化EXE
↓
ファイル投げ込み
↓
パスワードファイル　投げ込み
↓
a.exe 作成　完了

---------------------
「復号化」NG

a.exe　ダブルクリック
↓
パスワードファイル　投げ込み　←「パスワードを入力してください」　に
↓
▼パスワードがちがうか、ファイルが破損している可能性があります
復号できませんでした
↓
とエラーです

「注意」
パスワードファイルは「a.txt」 中身なし（空）のテキストファイル

「注意」
ちなみに、■アタッシュケース画面内では、
↓
a.exe　投げ込み
↓
パスワードファイル投げ込み　←「すでにパスワードファイルが入力済みです」　に
↓
正しく復号　完了

です

●「a.exe　ダブルクリック」では動きが違うのですね！？
これでは「アタッシュケース画面」がないと、使えませんが、、

対処などお願いします

**Comment by hibara** [comment]
ご報告ありがとうございます！

> １）パスワードの桁数
> ■ただし、パスワードの入力文字数には制限があり、
> ■大文字小文字を区別し、半角で32文字（全角だと16文字）以内です
> 
> 半角　５０桁　OK
> 倍角　３０桁　OK

こちらの制限はなくなりました。いくらでも長く入力することができます。
ヘルプページに昔の記載が残っていたため、そちらを修正させていただきました。

> ２）「パスワード入力」ができない
> 一旦パスワードファイルを使うと
> 
> もう「パスワード入力」ができない

修正いたしました。若干しょっぱいバグで申し訳ありません。

> ３）パスワードファイル入力で「復号化」エラー
> 
> 「暗号化」OK
> 「パスワードファイルのドラッグ＆ドロップを許可する」
> ↓
> 暗号化EXE

暗号化EXEの方にバグがありました。パスワードファイルをドラッグ&ドロップしても復号できないようでした。こちらも修正しました。

これらに対処した最新版を公開しました。↓

ver.3.2.0.0
https://hibara.org/software/attachecase/

よろしければお試しください。

なお、今後は１項目（バグ）＝１Isssueでお願いできますでしょうか。当方としてそちらの方が管理しやすく、たいへん便利になり助かります。Issueだらけになってもかまいませんので、できればよろしくお願いいたします。

**Comment by akibataro** [comment]
ご迅速なご対応助かります

＞１）パスワードの桁数
＞こちらの制限はなくなりました。いくらでも長く入力することができます。

素晴らしいです
●最高のセキュリティです。。

＞暗号化EXEの方にバグがありました。パスワードファイルをドラッグ&ドロップしても復号できないようでした。こちらも修正しました。

＞これらに対処した最新版を公開しました。↓

＞ver.3.2.0.0
＞https://hibara.org/software/attachecase/

＞よろしければお試しください。

有難うございます
さっそくバンバン使います。。


＞なお、今後は１項目（バグ）＝１Isssueでお願いできますでしょうか。
＞当方としてそちらの方が管理しやすく、たいへん便利になり助かります。
＞Issueだらけになってもかまいませんので、できればよろしくお願いいたします。

恐縮です
今後はそうします。。。
