### ISSUE TITLE
復号化で「更新日時」が変わってしまいます

### ISSUE THREAD

**Issue by akibataro** [hibara/AttacheCase3#30]
復号化で「更新日時」が変わってしまいます

「環境」
windows10 anniversary pro 64bit
atcs3200.zip AttacheCase.exe　←アタッシェケース#3　ver.3.2.0.0 - 2016/10/31   UPDATE! 

惜しいです。。

特定の１ファイルのみ(a.jpeg)
「更新日時」が変わってしまっています

■11,933ファイル　中の 1つです。。

どうしてですか？

後の11,932ファイル　は「更新日時」完全一致です。。
（.jpegファイルは多数ありますが、、、その他　b.jpeg、c.jpeg　などは変化しません
 .doc/.xls ファイルも多数あります）

--------------------手順

-------------
testフォルダ(11,933ファイル／1,039フォルダ 合計：2.55GB)
  「配下フォルダ」
   t1フォルダ
   t2フォルダ
   t3フォルダ　a.jpeg←「更新日時」2014/12/2 10:33:26
-------------

↓　暗号化

test.atc 作成正常完了

↓　復号化

■正常「復号」完了
-------------
testフフォルダ(11,933ファイル／1,039フォルダ 合計：2.55GB)
  「配下フォルダ」
   t1フォルダ
   t2フォルダ
   t3フォルダ　a.jpeg←「更新日時」2014/12/2 10:33:27 ▲1秒増えた！！
-------------

--------------------手順

「追記」
２回復号化しましたが、結果は同じです

●a.jpeg←「更新日時」2014/12/2 10:33:27 ▲1秒増えた！！

これです。。。
←このa.jpegだけです。。変なのは
中身見ても普通に表示できて特に、壊れていたりしません
普通のjpegファイルです。。。

ご対応お願いします

**Comment by akibataro** [comment]
試しに

7z　←7-Zip 16.04(2016-10-04) for Windows　64ビット x64

でやってみたら

a.jpeg←「更新日時」2014/12/2 10:33:26

　↓　zip 圧縮

a.zip　作成

　↓

解凍

　↓　
a.jpeg←「更新日時」2014/12/2 10:33:26●同じ

「更新日時」変わりませんでした。。

**Comment by hibara** [comment]
たびたびのご報告ありがとうございます！

ちょっとこちらでも様々な条件でテストしてみたのですが、1秒ズレのバグを再現することはできませんでした。。。

前述のご報告だと、単独でもその特定ファイルを暗号化→復号してもその問題は起こるのでしょうか？

あとは、少々お願いしにくいのですが、再現データの元となったファイルをいただけると大変ありがたいのですが・・・。

よろしくお願いいたします。

**Comment by akibataro** [comment]
>たびたびのご報告ありがとうございます！
>ちょっとこちらでも様々な条件でテストしてみたのですが、1秒ズレのバグを再現することはできませんでした。。。
>前述のご報告だと、単独でもその特定ファイルを暗号化→復号してもその問題は起こるのでしょうか？

YES

既に単独で試していました

a.jpeg←「更新日時」2014/12/2 10:33:26
１アフィル単独でいきなり再現します。。。


b.jpeg  ←正常です
c.jpeg  ←正常です


a.jpeg（556KB）
 と　
b.jpeg（565KB）

の違いが分かりません

●プロパティでみても同じです
（基本大きさが若干違う程度です。単なる文書のスキャンデータです）




>あとは、少々お願いしにくいのですが、
>再現データの元となったファイルをいただけると大変ありがたいのですが・・・。

恐縮です
作業で使っているので無理です。。。


頑張ってください

**Comment by akibataro** [comment]
これはOSの変な動きかもしれません
あるいはSSDの
あるはアンチウィルス系の。。


windows10 anniversary pro 64bit
SanDisk
AVAST
COMODO
Everything.exe


コピーしておいておいただけで
「更新日時」が
２秒変わりました。。。

--------------
昨日
a.jpeg←「更新日時」2014/12/2 10:33:26

↓

今日
a.jpeg←「更新日時」2014/12/2 10:33:28 ▲２秒増えた？？
--------------

こんなことがあり得ますか？？？


アンチウィルス系も怪しいですが、、
それなら、スキャンでもしたなら、、
↓
今日の日付　に変わりませんか？？？

不思議です。。

**Comment by hibara** [comment]
ご報告ありがとうございます！

こちらではまだ再現しておりませんので、推測となりますが、ファイルシステムがFAT32になったUSBメモリや、リムーバブルディスクからファイルをコピーすると、ファイルシステムのNTFS上で秒数が変化することがあります。

FAT32では、システムの仕様上、更新日時が偶数に丸められます。ですので、Windows OSのあるNTFSファイルシステムへコピーすると、秒数が変化してしまうことがよくあるようです。

となると、アタッシェケースではどうにも対応しがたく・・・しかしもう少し調査は続けようかとは思います。

ではよろしくお願いいたします。

**Comment by akibataro** [comment]
＞FAT32では、システムの仕様上、更新日時が●偶数に丸められます。
＞ですので、Windows OSのあるNTFSファイルシステムへコピーすると、
＞秒数が変化してしまうことがよくあるようです。



貴重な情報を有難うございます

基本いままでの現象は

■NTFS SSD でのことです。。。


が参考になりました

うっかり昨日FAT32になったUSBメモリに
コピーしようと思ってしまいました。。。

危なかったです。。
助かりました

＞しかしもう少し調査は続けようかとは思います。

お手数をおかけします。。


こちらもまた何か分かりましたらお知らせします。。

windows10 anniversary pro 64bit　のバグ？？？

**Comment by akibataro** [comment]
失礼しました

思い違いしました


--------------
昨日
a.jpeg←「更新日時」2014/12/2 10:33:26

↓

今日

a.jpeg←「更新日時」2014/12/2 10:33:28 ▲２秒増えた？？
--------------

は忘れてください
思い違いです。


間違って
FAT32になったUSBメモリ
にコピーしてしまったものを、
見てしまっていました。。

＞FAT32では、システムの仕様上、更新日時が偶数に丸められます。
＞ですので、Windows OSのあるNTFSファイルシステムへコピーすると、
＞秒数が変化してしまうことがよくあるようです。

まさに↑これですね。。多分▲２秒増えた　理由は？

失礼しました

**Comment by akibataro** [comment]
解決した感じです。。

「結論」タイムスタンプの壊れ　です　多分


http://www.vector.co.jp/soft/dl/win95/util/se479951.html

Change Timestamp

ctime031.zip

で正しく


-----------------------
a.jpeg←「更新日時」2014/12/2 10:33:26　●
-----------------------

と設定してみたら直りました
何度暗号化しても
１秒違いがもう出ません！！！！
←「更新日時」2014/12/2 10:33:26　のまま 27にならない


「原因」
単にこのファイルのみ

▲「更新日時」のタイムスタンプが壊れていたんですね！？

こんなことがあるのですね！
驚きました。。。

因みに
「更新日時」はどこに保存されているのでしょうか？
見てみたいです。。。壊れ具合を

分かりましたら、教えてください

**Comment by akibataro** [comment]
追記　難しいでしょうが、、、
●「タイムスタンプが壊れています」というメッセージは表示できますか？
↑
修復しますか？
↑
はい


など、できたら原因（修復）がすぐに分かってうれしいです。。。。

**Comment by hibara** [comment]
ご報告ありがとうございます！

そうですか。。。なかなかそのタイムスタンプの壊れたファイルを生成できずに四苦八苦しておりました。

> 因みに
> 「更新日時」はどこに保存されているのでしょうか？
> 見てみたいです。。。壊れ具合を

タイムスタンプは、暗号化されているため、通常は見ることができません。また、時間は、整数＋小数点で、ミリ秒単位で記録しているので、ぱっと見では分からないかもしれません。

タイムスタンプが壊れているかどうかという判定は難しいですね。そのズレが、本来のものなのか、壊れたものなのかという判定ができません（当然、所有者は分かるのかもしれませんが・・・）。

というわけで、よろしくお願いいたします。

**Comment by akibataro** [comment]
判定が難しですか、、、
では致し方ありません

ちなみに今回の件は、

アタッシュケースが

壊れた整合性のないタイムスタンプ

を利用（参照）したので起きた！

と思っていいのですか？？

●壊れた整合性のないタイムスタンプ
●のファイルなら必ず起きた！

ですか？？

**Comment by hibara** [comment]
残念ですが、そういうことになります。
申し訳ありません。。。

**Comment by akibataro** [comment]
わかりました
これはしょうがありませんね。。。。

**Comment by hibara** [comment]
申し訳ありませんが、ここでクローズさせていただきます。
