### ISSUE TITLE
ver.3.2.0.0 で暗号化すると実行形式が！

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#31]
ver.3.2.0.0  にしたら、暗号化すると実行形式が作られてしまいます。
以前のバージョンに戻しました。

**Comment by yukicon** [comment]
その後、ver.3.2.0.0 に戻して「現在の設定ファイルをINIファイルに保存」動作を行ったら .atc 形式になった。
それまでは、コマンドラインで /exeout=0 を指定しても駄目だった。

別件ですが /opf=1 効かなくなってしまって困りました。

**Comment by hibara** [comment]
ご報告ありがとうございます！

> ver.3.2.0.0 にしたら、暗号化すると実行形式が作られてしまいます。

> その後、ver.3.2.0.0 に戻して「現在の設定ファイルをINIファイルに保存」動作を行ったら .atc 形式になった。
> それまでは、コマンドラインで /exeout=0 を指定しても駄目だった。

こちらは、コマンドラインオプションの問題というより、初期状態の設定で暗号化を行おうとすると、自己実行形式になってしまっているようでした。ですので、一旦設定が保存されてしまえば正常になるようです。

また、
> 別件ですが /opf=1 効かなくなってしまって困りました。

こちらも、同様に関連付け実行がきちんと行われていないようでした。。。

いずれの件も修正したものを以下に公開しました。

ver.3.2.0.1
https://hibara.org/software/attachecase/

よろしけばお試しください。
ではよろしくお願いいたします。

**Comment by yukicon** [comment]
別のPCで ver.3.2.0.1 にしても暗号化すると実行形式が作られてしまいました。
「現在の設定ファイルをINIファイルに保存」動作を行っても変化なく焦りましたが、
常に選択する暗号化ファイルのタイプ：を一旦、「アタッシェケースのファイルタイプ ( *.atc )」から
「特に指定しない」にしたら治りました。

 /opf=1 の方は正常になりました。

因みに、アップデートは実行タイプのものではなく、zip タイプのものを利用させていただいています。

**Comment by hibara** [comment]
ご報告ありがとうございます！

推測ですが、

> 別のPCで ver.3.2.0.1 にしても暗号化すると実行形式が作られてしまいました。

この別PCは過去のバージョンで起動したことがあり、そのときの新規の設定データが残っていたりしませんでしょうか。

ご報告内にありますとおり、一度設定してしまえば、旧バージョンも新バージョンも再発することはありません。

ではよろしくお願いいたします。
