### ISSUE TITLE
「その回数を間違えたら暗号化ファイルを破壊する」　動作しません

### ISSUE THREAD

**Issue by akibataro** [hibara/AttacheCase3#32]
「その回数を間違えたら暗号化ファイルを破壊する」

動作していません
暗号化ファイルを破壊　しません

３回で破壊　設定
　↓　
a,exe　作成

------------------
１）a,exe ダブルクリック　単に３回間違いで終了
　←破壊なし

２）a,exe　画面へ投げ入れ
　←例外が発生しました。。。▲
　←破壊なし
------------------

ご対応お願いします

**Comment by hibara** [comment]
ご報告ありがとうございます！

基本的に自己実行ファイルの破壊は行わないようにしています。exe自身が自分を改変しようとすると、ほとんどのアンチウイルスソフトの検知に引っかかると思われるため、仕様上、行っておりません。

とはいえ、念のため、ファイル破壊オプションの動作を確認してみたところ、正常には行われていないことが分かりました・・・（通常の、*.atcでも破壊されない）。

ですので、その修正を入れたものを新たに公開しました。↓

ver.3.2.0.1
https://hibara.org/software/attachecase/

よろしければお試しください。
ではよろしくお願いいたします。

**Comment by akibataro** [comment]
有難うございます

*.atc
では破壊されました。。。
直っています

＞基本的に自己実行ファイルの破壊は行わないようにしています。
＞exe自身が自分を改変しようとすると、
＞ほとんどのアンチウイルスソフトの検知に引っかかると思われるため、仕様上、行っておりません。

そうでしたか、、

exeは単に３回間違いで終了するだけなのですね。。。

分かりました
