### ISSUE TITLE
アタッシュケースで作った zip ファイルは復号できますか？

### ISSUE THREAD

**Issue by akibataro** [hibara/AttacheCase3#34]
Ver 3.2.0.1

アタッシュケースで作った zip ファイルは復号できますか？

「想定外のファイルです。復号することができません」

ですが、、

---------------------
ファイル
↓
復号する
↓
a.zip 無理やり指定
↓
「想定外のファイルです。復号することができません」エラー
---------------------

単にVer 3.2.0.1　で
↓
「パスワードZIP」 指定
↓
作った zip ファイル ですが、、

**Comment by hibara** [comment]
毎度、ご報告ありがとうございます！

アタッシェケースでは、zip圧縮には対応しておりますが、オマケで入れたということもあり、解凍には今のところ対応しておりません。

理由としては、OSのデフォルト機能（Explorer）で開くことができ（ただし暗号化強度は低いPkzipWeakを選択する必要があります）、それに対応したアプリケーションも多いため、対応する必要がないかなと判断しています。

将来的に要望が多いようなら実装しても良いかな、とは考えております。

ではよろしくお願いいたします！

**Comment by akibataro** [comment]
有難うございます

分かりました

一言

「想定外のファイルです。復号することができません」
↓
「現状、zip ファイルの復号には対応していません」

などならわかり安いかもしれませんが、、、

**Comment by hibara** [comment]
> 「想定外のファイルです。復号することができません」
> ↓
> 「現状、zip ファイルの復号には対応していません」

なるほど！　たしかにおっしゃるとおりです。

次版以降で対応しようかと思います。いつもありがとうございます！

**Comment by akibataro** [comment]
助かります

**Comment by hibara** [comment]
先ほどこの問題に対応した最新版を公開いたしました。↓

ver.3.2.0.2
https://hibara.org/software/attachecase/

よろしければお試しください！

**Comment by akibataro** [comment]
有難うございます
バッチリです
助かりました
