### ISSUE TITLE
復号に失敗？

### ISSUE THREAD

**Issue by a-akasaka** [hibara/AttacheCase3#37]
暗号化した◯.atcを復号しようとしたところ，「オブジェクト参照がオブジェクト インスタンスに設定されていません」というメッセージが表示されて，エラーとなってしまいます。解決方法を教えてください。よろしくお願いします。

**Comment by hibara** [comment]
ご報告ありがとうございます！

アタッシェケースのバージョンは最新版をお使いでしょうか？
ver.3.2.0.2
https://hibara.org/software/attachecase/

また、特定のファイルのみ起こるのでしょうか？　それともすべて復号できないのでしょうか？

こちらでその事象が再現できないと直すことができないため、もう少しヒントのようなものがほしいです。もし可能であれば再現手順、または再現されるデータをいただけると嬉しいのですが・・・。

よろしくお願いいたします。

**Comment by a-akasaka** [comment]
回答が遅くなってしまってすみません。
暗号化したのは，一つ前のバージョンです。
復号は，一つ前のバージョンでも，最新版でもエラーが出ています。
同じエラーがでないものかと，何度か試してみましたが，再現はできませんでした。
１つのフォルダにまとめたデータを暗号化して，usbメモリーに保存しただけなんですが…

**Comment by hibara** [comment]
たびたびのご報告ありがとうございます！（何度もすみません・・・）

最新版（ver.3.2.0.2）では、以下のバグ修正が行われました。
> ルートディレクトリ上で暗号化したファイルを別の場所で復号しようとするとエラーになっていた問題に対処。

USBメモリをお使いだったということから、おそらくドライブレター直下（たとえば、'M:¥'といったルートディレクトリ上）で暗号化したことで、暗号化ファイルが壊れていたかもしれません。

おそらく最新版をお使いであれば、この問題は起きないと考えられますので、しばらくお使いいただいて様子を見ていただけますか。

何かあれば再度ご報告いただけると助かります。

ご不便をおかけして申し訳ありませんが、よろしくお願いいたします。

**Comment by a-akasaka** [comment]
ありがとうございます。
ということは，このエラーの出る暗号化ファイルは壊れており，復号は不可能ということでしょうか？

**Comment by hibara** [comment]
たしかにおっしゃるとおり復号できないのは問題ですね。。。

修正して正常に復号できるものを以下に公開しました。ver.3.2.0.1以前に作ってしまったファイルもきちんと復号できるはずです。

ver.3.2.0.3
https://hibara.org/software/attachecase/

よろしければお試しください！

**Comment by a-akasaka** [comment]
ありがとうございます。
おかげさまで，無事に復号できました。
少ない情報からエラーの原因を見つけ，すぐに対策を取っていただいたことに本当に感謝しています。
大変お世話になりました。
