### ISSUE TITLE
[希望] 暗号化したEXEファイルを復号する画面のUIの言語について

### ISSUE THREAD

**Issue by ym44** [hibara/AttacheCase3#38]
このたび初めてアタッシェケースをDLして利用させていただきました。
個人的に今後のご開発で加えていただけたら、と思うのは、
アタッシェケースのUI自体は「既定値/日本語/英語」と選べるのに、ここを「英語」に選択しても
EXE暗号化で、生成したEXEファイルを復号するときのUIは現状日本語オンリーになってしまうので、
ここもせめて英語が選択できる、または最初から和英両方表示するように、という点です。
「パスワードを入力してください:」= 「Enter password:」
「パスワードを表示」= 「Show characters」
「復号/元に戻す」=「Decrypt」
「終了」=「Exit」　と表示されるように、です。
ここに英語表示が入ったら、日本語が読めずアタッシェケースをインストールしていない外国人宛にも
暗号化ファイルを送ることができるようになります。
ソースコードがあっても私にはプログラミングの知識もありません。ご検討いただけたら幸いです。

**Comment by hibara** [comment]
ご報告ありがとうございます！

EXEの実行ファイル形式は、一応ローカライズには対応しておりまして、英語環境で実行すると、UIはすべて英語になるはずです（で、なければバグです）。

相手はアタッシェケースを持っていない場合が多く、設定に頼ることもできないので、実行される環境のロケールだけを見て、勝手に日本語版、英語版と切り替えています。

英語環境にて今一度ご確認いただけますでしょうか。ではよろしくお願いいたします。

**Comment by ym44** [comment]
早速のご返答ありがとうございます。
当方、英語版のWindowsとか持っていないので、安直な方法ですが、
Windows10用の英語（米国）とフランス語の言語パックをインストールして、
表示言語（といってもデスクトップ以降のみのようです）をそれぞれに変更して試したところ、
いずれの場合もたしかにInput passwordというように英語で表示されることを確認できました。
設計上はロケールが日本語以外ならすべて英語表示になる、という理解で間違いないでしょうか。

**Comment by hibara** [comment]
そうですね。内部的には「日本語」環境でなければ、すべて英語になるという仕様になっております（作者が辛うじて書ける言語なもので・・・）。

**Comment by ym44** [comment]
よくわかりました。ちょっと私が手助けする相手がオランダ人に送るというので念のためにお尋ねしてみたのですが、私がオランダ語ができなくても、オランダ人はきっとよく英語がわかるはずなので行けると思います。このたびはありがとうございました。
