### ISSUE TITLE
INIファイルがあるとコマンドラインが機能しない

### ISSUE THREAD

**Issue by ousinousin** [hibara/AttacheCase3#39]
アタッシェケースにいつもお世話になっております。
コマンドラインでの使い勝手と、本体にパスワードを保存できることでコマンドラインにパスワードを入れずに済む点が特に気に入っています。

表題の件について、先ほどver.2.72からver.3.2.1.0にバージョンアップしたのですが、
「現在の設定をINIファイルに書き出す」を使って「_AtcCase.ini」を生成するとコマンドラインが機能しないように思います。
たとえば、"C:\test\atcs3210\AttacheCase.exe C:\test\テスト.txt"というショートカットを作成して実行すると、アタッシェケースは起動するのですが"テスト.txt"の暗号化は実行されません。
しかし、「_AtcCase.ini」を削除してから上記のショートカットを実行すると"テスト.txt"の暗号化が実行されます。

当方でコマンドラインやINIファイルの使い方を勘違いしているおそれもありますが、
もしバグでしたら修正をご検討頂ければ幸いです。

**Comment by hibara** [comment]
ご報告ありがとうございます！

本来の仕様は、

レジストリ < INIファイル < コマンドラインオプション

と優先順位がついていて、それぞれが順に上書きされていくという仕様なのですが、内部的にそのような順番になっていなかったようです。

そこで修正を加えたものを以下にアップロードいたしましました。
よろしければお試しいただければと思います。

ver.3.2.1.1
https://hibara.org/software/attachecase/

ではよろしくお願いいたします。

**Comment by ousinousin** [comment]
「_AtcCase.ini」を生成した状態でコマンドラインが機能することを確認しました。
修正頂きありがとうございました。
また便利に利用させて頂きます。
