### ISSUE TITLE
圧縮設定

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#4]
1.オプションの圧縮設定が反映されないようである
2.オプションの圧縮設定を変更しても保持されない
3.コマンドラインからも反映されないようである

AttacheCase.exe /exit=1 /ow=0 /withext=1 /comprate=9 [path]abc.txt

0～9まで変化させても暗号化されたファイル・サイズに変化がないようです。
簡単なテキストファイルにて暗号化を行ったためかも知れません。

**Comment by hibara** [comment]
圧縮のコマンドラインオプションというより、本体の圧縮機能自体動作しておりませんでした・・・つまり無圧縮状態で暗号化されていただけですので、以下の最新版から、コマンドラインオプションからも行けると思います。

https://hibara.org/software/attachecase/

**Comment by yukicon** [comment]
やはり無圧縮状態でしたか。
コマンドラインオプションから可変設定できることを確認いたしました。
