### ISSUE TITLE
複数のファイルをまとめる場合のファイル名

### ISSUE THREAD

**Issue by sakamotoj** [hibara/AttacheCase3#40]
設定で「複数のファイルを一つにまとめる」を指定した場合に、「暗号化ファイル名の書式設定」を指定している場合でも、複数ファイルの最初のファイル名＋拡張子になってしまいます。
暗号化ファイル名の書式設定には「\<date:yyyyMMdd_HHmm\>\<ext\>」を指定しています。

一度確認お願いできますでしょうか？

**Comment by hibara** [comment]
ご報告ありがとうございます！

確認を行ったところ、再現することができませんでした・・・。とはいえ、「複数のファイルを一つにまとめる」にチェックを入れていると、ファイル名を指定するダイアログは出てしまいますが（これも妙な感じがしますが）、その後へ進むと、正常に上記の日付＋拡張子でファイル出力されました。

よろしくお願いいたします。

**Comment by sakamotoj** [comment]
こちらでは何度やっても再現しますね・・・
複数ファイルの場合→通常の場合は、暗号化ファイルの書式設定が有効になりますが、複数ファイルの場合→複数のファイルを一つにまとめるにすると、元のファイル名がファイル保存ダイアログのデフォルトになります。また、暗号化ファイルのタイプを自己解凍形式にしていても、拡張子偽装をしていても元のファイル名（拡張子もそのまま）が表示されます。
OSはWin8.1、.netFrameworkは4.0.30319となっています。
何か調べようがありそうでしょうか？

**Comment by sakamotoj** [comment]
ソースをのぞいてみましたが、Form1.csの2928行目、FileList[0]をFileNameにセットしており、getSpecifyFileNameFormat()を噛ませていないので、元のファイル名そのままになりそうな気がしますがどうなんでしょうか？
（このコードを通るのにお伝えしている発生条件に漏れがあったらすいません）

**Comment by hibara** [comment]
いろいろとご指摘ありがとうございます！

けっきょくのところ、自動で暗号化ファイル名を決定しているのに、その前でファイル名を改めて入力させるのはどうなの？というところが、僕の中でありまして、自動で暗号化ファイル名を付けるように設定している場合は、フォルダー名を入力するダイアログは表示されないように改良いたしました。

ver.3.2.1.1
https://hibara.org/software/attachecase/

よろしければお試しください。

**Comment by sakamotoj** [comment]
ありがとうございます。
確認したところ、複数ファイルのファイル名については問題ありませんでした。
別件で気になったところがありますので、別issueで上げますね。
