### ISSUE TITLE
複数のファイルを一つにまとめた際、復号時に不要なフォルダが作成される

### ISSUE THREAD

**Issue by sakamotoj** [hibara/AttacheCase3#41]
複数ファイルを一つにまとめる設定をして複数ファイルを暗号化した際、復号時に暗号化ファイル名と同じ名前のフォルダが作成されます。
また、復号されたファイルは作成されたフォルダ内ではなく同一階層に作成されるため、不要なフォルダが作成されている感じになります。

自己解凍の場合は「復号時に親フォルダーを生成しない」設定に関わらずフォルダ作成されますが、atcファイルの場合は「復号時に親フォルダーを生成しない」設定をしていない場合のみ発生します。（「復号時に親フォルダーを生成しない」設定をしている場合はフォルダ作成されない）

確認よろしくお願い致します。

**Comment by hibara** [comment]
何度もありがとうございます！

申し訳ありませんが、これに関しては仕様です。「複数ファイルを一つにまとめる」というのは、同一階層のファイルをまとめるだけでなく、バッチファイルなどで、あちこちのファイルを持ってきてまとめる際にも使われますので、親フォルダーはどうしても必要ということになります。

そのため、暗号化の際に、一つにまとめるフォルダー名を命名させる仕様が入っていたのは、実は正しい処理で、自動で暗号化ファイル名を設定するオプションがONの状態のときに、そのダイアログ表示がスキップされるというのは例外的と考えています。

恐れ入りますがよろしくお願いいたします。

**Comment by sakamotoj** [comment]
なるほど、了解しました。
以前使用していたバージョン2系ではそのような動きではなかった気がするので、動作が変わっていたんですね。
ただ、復号の結果フォルダが空だった場合は削除するなどの処理があればなおいいかもしれませんね。
