### ISSUE TITLE
ver.3のコマンドラインオプション指定実行で暗号化が自動実行されない

### ISSUE THREAD

**Issue by gh-k-murata** [hibara/AttacheCase3#42]
お世話になります。

ver.3.2.1.2を以下のコマンドラインオプションで実行し、バッチでファイルの暗号化を自動実行しようとしています。

/p=1234567 /exit=1 /front=0 /exeout=0 /en=1 /saveto="%TRG_FOLDER%" /ow=0 /allpack=1 /oneby=0 /nopfldr=1 /del=1 /chkdel=0 /delrand=0 /delnull=0

バッチの実行時「コマンドラインオプションからのパスワード：」の画面で待ち状態になり、暗号化が開始されません。
この状態で暗号化ボタンをクリックすると暗号化が一瞬で完了しますが、出力フォルダに暗号化ファイルは作成されず、アタッシェケース自体も終了されません。

ver.3を自動実行するための設定で、不足やおかしな点がありましたら教えて頂けますでしょうか？

ちなみに、上記のバッチ運用はver.2の頃より実施してきたものです。
ver.3への変更は、ver.2.8.2.8で暗号化したファイルの一部が復号化に失敗する事に最近気づいたためで、問題のファイルを復号化する際に以下のエラーが発生します。
「保存する先のファイルに書き込めません。復号化できません。」

復号化に失敗するのは暗号化するファイルのサイズが原因と思われます。
失敗するファイル：　元のサイズ「2.08 GB」　暗号化後のサイズ「341 MB」
成功するファイル：　元のサイズ「801 MB」　暗号化後のサイズ「231 MB」

ver.2.8.3.0での復号化も試しましたが同じ状況でした。
ver.3.2.1.2では正常に復号化できています。

なお、上記の現象は下記のOSでの発生を確認しています。
Windows Server 2008 R2 SP1
Windows Server 2012
Windows Server 2012 R2

以上、よろしくお願い致します。

**Comment by hibara** [comment]
ご報告ありがとうございます！

> バッチの実行時「コマンドラインオプションからのパスワード：」の画面で待ち状態になり、暗号化が開始されません。

以下のコマンドラインオプションを追加してみてください。

/mempexe=[0,1]
記憶パスワードで確認なく実行する
ex). /mempexe=1 ※実行せず確認を行いたい場合は、ex). /mempexe=0

> ver.3への変更は、ver.2.8.2.8で暗号化したファイルの一部が復号化に失敗する事に最近気づいたためで、問題のファイルを復号化する際に以下のエラーが発生します。
> 「保存する先のファイルに書き込めません。復号化できません。」

これは前のとは別のIssueですかね？
これに関しては、ver.2に潜在的にあったバグです。正常に復号できているver.3で復号していただけたらと思います。

ではよろしくお願いいたします。

**Comment by gh-k-murata** [comment]
回答ありがとうございます。

> 以下のコマンドラインオプションを追加してみてください。
> 
> /mempexe=[0,1]

 /mempexe=1 の追加でパスワードを聞かれなくなりました。
あと /autoname の設定を追加しましたところ、バッチでの自動実行ができる様になりました。
（ver.2ではバッチでも本体側も未指定でしたが、なぜか動いていました。）
オプションが長くなってきましたので、/list オプションの様にバッチ用に作成したiniファイルを読み込めると良いかなと思いました。

ちなみに、ver.2では暗号化ファイルをワイルドカードで指定していましたが、ver.3だとうまく動きませんでしたので、対象のファイルのみ格納するサブフォルダを作成し、フォルダ単位で暗号化する様にしました。

> これは前のとは別のIssueですかね？
> これに関しては、ver.2に潜在的にあったバグです。正常に復号できているver.3で復号していただけたらと思います。

いいえ、ver.2のマニュアルにはファイルサイズの制限がFAT32 では4GB または2GB とありましたが、こちらの環境はNTFSでしたので、別の問題なのかと思って報告のつもりで書きました。
ver.3に移行しますので、ver.2の件についての対応は特に必要ありません。

以上、よろしくお願い致します。

**Comment by y-morigou** [comment]
始めまして、よろしくお願いします。
いつもアタッシェケースを利用させていただき有難うございます。
会社のサーバにある数千個の各種ファイルをファイル単位で暗号化しています。

私もver.2では自動実行できたのですがver.3.2.1.3で出来なくなりました。
当初のこの質問の回答を楽しみにしていたのですが解決しない状態です。
VBAのソースは次の通りです。 /autonameはパラメータの入力形式が分からないので
今時点では取り込めていません。
エラーは「AttacheCase3は動作を停止しました」です。
 動作環境はwindows7です。

Private Sub angou_Click()
Dim rc As Long
Dim atcexe, mfile

'アタッシェケースのシステム保存場所
'atcexe = "C:\Program Files (x86)\AttacheCase\AttacheCase.exe "
atcexe = "C:\Program Files (x86)\AttacheCase3\AttacheCase.exe "

'暗号化前ファイル指定
mfile = "C:\Users\morigou\Desktop\test\各種出席者名簿原本.xls"

rc = Shell(atcexe & mfile & " /mempexe=1 /ow=1 /exit=1 /del=1 /en=1")

MsgBox "終了しました。"

End Sub

アドバイスをお願いします。

**Comment by hibara** [comment]
ご報告ありがとうございます。

早速、こちらで同様のバッチファイルを作成し試しましたが、問題なく起動できました。他に影響する設定項目があるか、VBAの記述自体に問題があるとは考えられないでしょうか。

よろしくお願いいたします。

**Comment by y-morigou** [comment]
早速のコメントありがとうございます。
今時点では自宅のPCと会社の私のPCどちらも暗号化できません。
明日会社で複数のPCで試して結果をアップします。

よろしくお願いいたします。

**Comment by y-morigou** [comment]
メールありがとうございます。

先に問い合わせ窓口を見させていただきましたのでコメントしておきました。

恐れ多くも開発者様からメールが戴けるなんて驚いています。


先のお尋ね窓口にお話したとおり我が社ではサーバ内のお客様情報ファイルは全てアタッシュケースで暗号化することが義務付けられています。
（フォルダー単位で暗号化すると特定ファイルを探すのが困難。暗号化と複合化に多くの時間を要す）

アタッシュケースの利用状況は下記のとおりです。

全ファイル暗号化の取り組み（一度だけ）（プロジェクトチームを作り取り組んだ）
（１）暗号化対象ファイルに読込み専用が存在するかの把握と対策。（ツールでファイル化）

（２）暗号化対象フォルダ名に半角のブランクが存在した場合アンダースコア(_)に置き換える。（ツールで置換）

（３）暗号化対象ファイル名に半角のブランクが存在した場合アンダースコア(_)に置き換える。（ツールで置換）

（４）特定フォルダー毎に全ファイルの暗号化を実施（ツールで実施。30,000ファイルで90分位で特定フォルダーの数は40個位）

　　　＊半角のブランクでも手動実行時はそのまま暗号化できます。
　　　＊フォルダー名やファイル名に半角のブランクを使うこと事態が異常かもしれませんが数多く存在していた。

日々の取り組み
（１）ファイルは必要の都度、複合化して使いますが退社時にツールでフォルダーを指定しますと複合化ファイルだけが暗号化されます。
　　　（特定フォルダ内に30,000ファイルが存在して複合化ファイルが100の場合でも15秒位で暗号化できます）

なおver.2での暗号化時 /del=1で元ファイルか消去できないPCが存在したので同名の暗号化ファイルが出来ていれば強制削除するようにしています。（問題ない）

上記のような状態で我が社にとりアタッシュケースはなくてはならない存在の毎日で重宝に使わせていただいております。
ほんとに有難うございます。
今後ともよろしくお願いいたします。　



---- 元のメッセージ -----
差出人: Mitsuhiro Hibara <notifications@github.com>
宛先: hibara/AttacheCase3 <AttacheCase3@noreply.github.com>
Cc: y-morigou <morigou_2005@mail.goo.ne.jp>, Comment <comment@noreply.github.com>
送信済み: Sat, 04 Feb 2017 07:52:34 +0900 (JST)
件名: Re: [hibara/AttacheCase3] ver.3のコマンドラインオプション指定実行で暗号化が自動実行されない (#42)

ご報告ありがとうございます。

早速、こちらで同様のバッチファイルを作成し試しましたが、問題なく起動できました。他に影響する設定項目があるか、VBAの記述自体に問題があるとは考えられないでしょうか。

よろしくお願いいたします。

**Comment by y-morigou** [comment]
このコーナーと個人あてのメールがリンクしているのが分からなくて失礼しました。

今日会社で複数のPCで試してみましたがver.3.2.1.3では暗号化できませんでした。
一つ気になるのはver.2とver.3.2.1.3を併用していることです。
ver.3.2.1.3は暗号パスワードと複合化パスワードを設定で固定化しています。
何かお気づきの事が有りましたらアドバイスをお願いします。
とりあえずver.2ではOKなので、このまま現状維持したいと考えています。
よろしくお願いします。

**Comment by y-morigou** [comment]
いろいろ試した結果、次のことが判明しました。

①rc = Shell(atcexe & mfile & " /mempexe=1 /ow=1 /exit=1 /del=1 /en=1")
②rc = Shell(atcexe & mfile & " /mempexe=1 /ow=1 /exit=1 /del=1 /en=1",1)

ver.3.2.1.3で実行した場合①は前に述べた通りで②はOKとなります。

できれば画面表示はしたくないので①で実行するなにか設定があれば教えて下さい。
よろしくお願いします。

**Comment by hibara** [comment]
前にも申し上げましたが、VBAではなくて、バッチファイルにしたとき正常に動作しますでしょうか？　もし正常に動作するのであれば、VBA側の問題と切り分けられます。

「アタッシェケース」のIssueでVBAに関する問題は語るべきではないような気がします。また、僕自身もVBAにまで踏み込んでの調査は行いたくありません。

よろしくお願いいたします。

**Comment by gh-k-murata** [comment]
元の問い合わせを書いたものです。
私の方の問題は解決していますが、解決の参考になれば幸いです。

1. /autoname の設定

/autoname については、こちらは複数のファイルをまとめて暗号化する関係で、未設定だと暗号化ファイル名を指定するダイアログが表示され、バッチ実行が止まりますので追加しました。
/autoname の設定は設定画面が参考になると思います。フォーマットに "<" ">" ":" が含まれますので""で囲む必要があります。
`  例: /autoname="<filename>_<date:yyyy_mm_dd><ext>"`
なお、こちらでは上記のフォーマット指定ではなく、出力先ファイル名をバッチ側で生成して直接設定する様にしました。
`  例: /autoname="%savefile%.atc"`

2. アタッシェケースの非表示実行

アタッシェケースには画面を非表示にするオプションがありませんので、画面が非表示状態での実行は本来想定されていない挙動ではないでしょうか？
代替案として、常にウィンドウを最小化して処理する /wmin=1 オプションを使用するのはどうでしょう？

以上、ご参考まで。

**Comment by y-morigou** [comment]
お二人の方有難うございます。
バッチファイルでの検証は早速実行してみます。

**Comment by y-morigou** [comment]
結果が遅くなり申し訳ありませんでした。
今日ver.2とver.3をバッチファイルで試験をしてどちらも正常であることを確認しました。
また、日常の暗号化もver.3で使わせていただいております。
ほんとに有難うございました。
