### ISSUE TITLE
AD RMSにより暗号化されたファイルを含む.atcファイルの復号化について

### ISSUE THREAD

**Issue by privango** [hibara/AttacheCase3#46]
.atcファイルを復号しようとしたところ。「パスワードがちがうか、ファイルが破損している可能性があります。復号化できませんでした。」とのメッセージが出力されました。
暗号化した際のファイルを思い返したところ、microsoftのActive Directory Rights Management (AD RMS) により
管理されているファイルが含まれていました。
さらに、 AD RMSにより管理された.atcファイルを、暗号化対象として含んでいるかもしれません。
このようなケースでの動作レポートなどはございませんでしょうか？

https://technet.microsoft.com/ja-jp/library/cc771627(v=ws.11).aspx

**Comment by hibara** [comment]
ご報告ありがとうございます。

> AD RMSにより管理された.atcファイルを、暗号化対象として含んでいるかもしれません。
このようなケースでの動作レポートなどはございませんでしょうか？

そのようなケースでの動作報告はいただいたことがありません。

> 「パスワードがちがうか、ファイルが破損している可能性があります。復号化できませんでした。」とのメッセージが出力されました。

結論から言えば、エラーの表示メッセージを見るかぎりでは、そのままのことが起きているかと思います。
