### ISSUE TITLE
復号途中のエラーについて

### ISSUE THREAD

**Issue by ronpa5** [hibara/AttacheCase3#47]
復号途中で、エラー（復号ファイルのチェックサム値エラー）がでて数％で停止してしまうため
動作設定のデータのサルベージ機能を利用しようとしているのですが
チェックボックスを選択しても適用はグレーアウトのままで
その状態でOKを選択して、再度動作設定を開くとチェックボックスが外れています。
本機能の利用方法または、エラー時に停止せず復号化させる方法があれば
教えていただけませんでしょうか

暗号化及び復号化　Ver 3.226
対象ファイル1.5G程度（エクセル等ファイルが沢山あるフォルダ以下を暗号化）
Windows10

**Comment by hibara** [comment]
たしかに「データのサルベージ」機能の設定が正常に保存されないという不具合がありました。修正した新しいバージョンを公開いたしましたので、よろしければお試しください。

https://hibara.org/software/attachecase/
