### ISSUE TITLE
複数ファイルを一括で復号化した際のエラーについて

### ISSUE THREAD

**Issue by tachibanajin** [hibara/AttacheCase3#48]
いつもアタッシェケースを使用させていただき大変重宝しております。

アタッシェケースで複数ファイル(10ファイル位)を一括復号した際、
下記のエラーが出る場合がございます。(再現性有り)
![170726](https://user-images.githubusercontent.com/30456584/28604576-9a01e46e-7206-11e7-9516-486231e244f3.png)

このエラーが出た場合、正しく復号されていない可能性はありますでしょうか？

また上記エラーとの関連性は不明なのですが、
復号時にエラーが出た時、ファイルサイズが変わってしまう現象がありました。
※本来19.6KB(20,109バイト)のテキストファイルが4.00KB(4,096バイト)になっておりました。

ファイルサイズが変わる現象は再現性がない為、アタッシェケースが要因かは不明なのですが、
何か心当たりがあればご教示いただければと思います。

どうぞよろしくお願いいたします。

**Comment by tachibanajin** [comment]
エラーの再現性を確認していた所、再現性が有りましたので
こちらのバグの確認・修正をお願いいたします。

4KB以上のファイルを暗号化
↓
上記ファイルを復号化
↓
再度上記ファイルを復号化

この時に下記問い合わせ画面が表示されます。
![170726](https://user-images.githubusercontent.com/30456584/28605797-7f6ace06-720e-11e7-9b1c-84587afd85e0.png)

この時にキャンセルを押すとサイズが4KBに変更され、4KB以上のデータを削除してしまいます。

ご確認いただければと思います。
どうぞよろしくお願いいたします。

**Comment by hibara** [comment]
ご報告ありがとうございます！

バグの再現方法がきちんとあったため、修正が非常に行いやすかったです。助かりました。
結局「キャンセル」の指示が、きちんと復号処理プロセスへ届いていなかったのが原因だったようです。

上記問題を修正したものを以下に公開いたしました。よろしければお試しください。
https://hibara.org/software/attachecase/

**Comment by tachibanajin** [comment]
ご確認いただきありがとうございます。
こちらでも最新バージョンでバグの発生しなくなった事を確認いたしました。
修正いただきありがとうございました。

また、複数ファイルの一括復号時に発生したエラーについてですが、
何が原因で発生するのか、どのようなエラー現象が起こりうるのか、
こちらも分かりましたらご教示いただければと思います。

どうぞよろしくお願いいたします。

**Comment by hibara** [comment]
> また、複数ファイルの一括復号時に発生したエラーについてですが、
> 何が原因で発生するのか、どのようなエラー現象が起こりうるのか、
> こちらも分かりましたらご教示いただければと思います。

こちらですが、いろいろな条件で複数ファイルを同時復号してみましたが、どうしても再現いたしません。。。どういったタイミングでエラーが発生するのでしょうか？

また、再現できるサンプルファイル等いただけるとたいへん助かるのですが・・・可能であればよろしくお願いいたします。
