### ISSUE TITLE
暗号化完了後に元ファイル削除を指定しても元ファイルが削除されない場合がある

### ISSUE THREAD

**Issue by VZMNAPZO** [hibara/AttacheCase3#49]
AttacheCaseにつきましては長い間お世話になっており大変重宝させていただいております。
以前から暗号化のときは元ファイルを完全削除する運用で使っておりましたが、AttacheCase3から元ファイルが残ってしまう場合が発生します。残っている元ファイルは、ファイル内容がランダム上書きで既に書き換えられている場合や、まったく書き換えられず元のままの場合だったりします。
当方の環境は、Windows10(32bit)、AttacheCase3(Ver3.2.3.0)です。
また、削除の指定は「メインウィンドウに削除のチェックボックスを表示」「暗号化後に削除確認メッセージを表示」「完全削除指定：ランダム1回・ゼロ0回」です。

**Comment by hibara** [comment]
ご報告ありがとうございます！

> AttacheCase3から元ファイルが残ってしまう場合が発生します。

これはどういった条件等で起きやすいでしょうか（複数ファイルをまとめてドラッグ＆ドロップするとか）。こちらで何度か試した限りでは再現ができなかったです・・・

再現のヒントがあれば、修正につながるのですが・・・もう少し何かあれば、よろしくお願いいたします。

**Comment by VZMNAPZO** [comment]
早々のご返事ありがとうございます。お尋ねの件についてお答えします。
当方でほぼ起きる条件は、
１、暗号化対象ファイルが比較的大きいサイズ（数ＭＢ）のExcelやJPGやTXT。
２、暗号化はWindowsエクスプローラーから右クリック「送る」で１ファイルのみを指定（尚、ファイルのある階層はそれほど深くないです。「ドキュメント」のすぐ下のフォルダーやデスクトップです。）
３、暗号化パスワードは保存（因みに復号化パスワードは保存していません）
４、暗号化のオプション設定は「同じ名前のファイルが・・・」にチェック、「複数ファイルの場合」は「通常」、「オリジナルの・・タイムスタンプを保持する」にチェック、「暗号化ファイルに拡張子を含める」にチェック。
５、削除のオプション設定は、「暗号化完了後に元ファイルを削除する」「メインウィンドウに削除のチェックボックを表示する」「暗号化後に削除確認メッセージを表示する」すべてチェック、高度な削除設定は「完全削除」チェックでランダム1回、ゼロ0回。（尚、この書き込み回数は別の指定でも同一不具合は発生します。）
その他、セキュリティソフトはアバストインタネットセキュリティを使用。但し、アバストを無効にしてテストしましたが不具合は発生します。
以上です。調査のほどよろしくお願いいたします。

**Comment by hibara** [comment]
詳細なご回答ありがとうございます。
いただいた条件にて、いろいろとテストしてみましたが、こちらでは再現いたしません・・・

ひょっとしたら特定のファイルにおいて起きるのでしょうか？

もし可能であれば再現可能のサンプルファイル等をいただけると助かるのですが・・・

**Comment by VZMNAPZO** [comment]
ここからファイルを送る方法が判らなかったので、メールにて送らさせて頂きました。
よろしくお願いします。

**Comment by hibara** [comment]
早速のご対応、ありがとうございます！　受領いたしました。

ただ、やはり再現しません・・・こちらでは２ファイルともに正常に削除されました。

VZMNAPZOさんと僕の環境では何かが異なっているということでしょうか。
申し訳ありませんが、現時点では修正が難しいと判断せざるを得ません。

**Comment by VZMNAPZO** [comment]
色々と調査して頂きありがとうございます。
現状では修正困難との事、拝承したしました。
こちらの環境がWin7(32Bit)からWin10(32bit)にUpgradeした変則PCなので、そのあたりに原因があるのかも知れませんね。
処理の流れとしては暗号化→元ファイル削除問合せ→完全削除開始→元ファイルへの書き込み処理完了までは正常に処理されているようです。その後の「元ファイル名削除処理」を失敗しているように思います。この処理において32bitのWin7からWin10に上げたWindowsのファイルエクスプローラまわりの何等かの不具合と干渉しているのかも知れませんね。
とりあえず、別の「完全削除」ソフトを使って元ファイルを削除する運用で対処することにします。
ありがとうございました。

**Comment by hibara** [comment]
お役に立てずに申し訳ありません。
よろしくお願いいたします。
