### ISSUE TITLE
パスワード確認無しに記憶パスワードで実行後にハング

### ISSUE THREAD

**Issue by Kamakura-Taro** [hibara/AttacheCase3#5]
お世話になります。

「動作設定」の「一般」→「パスワード」項目で、3項目にチェックを入れて暗号化処理をすると、暗号化ファイルはできますが、その後は「終了」処理しかできなくなります。

また、「暗号/復号時に確認無しに記憶パスワードで実行する」のチェック情報は保持されません。

**Comment by hibara** [comment]
いろいろとご報告ありがとうございます！

上記の設定周り、実際の挙動含めまして新版にて修正いたしました。以下からダウンロードしてお試しいただければと思います。

ver.3.0.1.6
https://hibara.org/software/attachecase/

**Comment by Kamakura-Taro** [comment]
対応をありがとうございました。

確認いたしました。

尚、https://hibara.org/software/attachecase/#download-betaには、現在
ダウンロード（正式版 Ver.3）
2016/09/18 - ver.3.0.1.**_9_**
となっています。
