### ISSUE TITLE
「パスワード文字列を隠さず入力する」にチェックを入れていないのに常に「隠さず入力」になる

### ISSUE THREAD

**Issue by VZMNAPZO** [hibara/AttacheCase3#50]
AttacheCaseにつきましては長い間お世話になっており大変重宝させていただいております。
「パスワード文字列を隠さず入力する」にチェックを入れても入れなくても、パスワード入力ボックスの文字列は常に丸見え（隠れていない）状態となってしまいます。AttacheCase3からのバグだと思われます。当方の環境は、Windows10(32bit)、AttacheCase3(Ver3.2.3.0)です。

**Comment by hibara** [comment]
ご報告ありがとうございます！
こちら、少々かっこ悪いバグですね。現象を確認いたしました。次版では修正されるはずです。

それにしてもどうしてこのバグが、今まで報告されずに来たのでしょう・・・謎

**Comment by VZMNAPZO** [comment]
早々のご返事ありがとうございます。
私もあまりにも判りやすい症状なので、こちらが何か設定ミスをしているのだろうと思い報告をためらいました。
修正していただけるとの事、ありがとうございます。

**Comment by hibara** [comment]
だいぶお時間をいただいてしまって申し訳ありません。

先ほどこの問題を修正した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/

**Comment by VZMNAPZO** [comment]
修正ありがとうございます。
