### ISSUE TITLE
Ver.3230のコマンドラインオプション指定実行で復号化が出来ません

### ISSUE THREAD

**Issue by ms-suzuki** [hibara/AttacheCase3#51]
Ｖer.3.2.3.0で以下のコマンドラインオプションで実行し、バッチでファイルの復号化が出来なくて困っております。

AttacheCase.exe "C:\DATA\TEST.exe" /p=1234567890 /exit=1

※AttacheCase.exeの導入場所はパスを通しております。

コマンド実行後は、デスクトップ上にパスワードが入力された画面が立ち上がったまま止まっております。
Ｖｅｒ2では上記コマンドで復号化が出来ておりました。

復号を実行する上で、設定不足やコマンドラインオプションの不備等ございましら教えて頂けないでしょうか？

なお、上記の現象は下記のOSでの確認しております。
Windows Server 2012
Windows Server 2012 R2

以上、宜しくお願い致します。

**Comment by hibara** [comment]
/mempexe=1
記憶パスワードで確認なく実行する

を付加したら、できませんか？
よろしくお願いいたします。

**Comment by ms-suzuki** [comment]
ご回答頂き、誠にありがとうございます。
/mempexe=1 のコマンド追加することで無事に復号ができました。

尚、復号化が成功した時のオプションは以下の通りです。
AttacheCase.exe "C:\DATA\TEST.exe" /mempexe=1 /p=1234567890 /exit=1

以上、宜しくお願い致します。
