### ISSUE TITLE
復号時にすべて上書きが機能しません

### ISSUE THREAD

**Issue by un-nondry** [hibara/AttacheCase3#52]
お世話になっています。

Ver3.2.3.0で復号時に「すべて上書き」を選ぶのですが単なる「上書き」として処理されているようで
上書きファイルがあるたびに処理方法を聞かれます。
修正お願いいたします。

**Comment by hibara** [comment]
ご報告ありがとうございます！

おそらく最新のバージョンでは直っていた可能性がありますが、先ほどさらに細かい修正などを行った最新版の方をアップロードさせていただきましたので、下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/
