### ISSUE TITLE
上書き確認ダイアログをESCで消せるようにできませんか？

### ISSUE THREAD

**Issue by dunedist** [hibara/AttacheCase3#53]
お世話になります。
アタッシェケースを（誇張ではなく）毎日利用させていただいて大変感謝しております。
一点ご検討いただきたいことがありまして。
旧バージョンでは上書きの確認ダイアログを ESC キーで消すことができましたが
新バージョンでも同様の動きにしていただくことはできないでしょうか。
パスワードを間違えていないか念のため新たに作成した暗号ファイルを開いてみて
ESC キーでキャンセル、という操作をよく行うもので。
ご検討いただけましたら幸いです。

**Comment by hibara** [comment]
ご報告ありがとうございます！

先ほどこれについて対応した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/

**Comment by dunedist** [comment]
確認が遅くなってすみません。
希望通りの動作になりました。
対応いただきありがとうございました。
