### ISSUE TITLE
二重起動するとアプリ終了時にReleaseMutexで落ちる

### ISSUE THREAD

**Issue by misobit** [hibara/AttacheCase3#54]
V3.2.3.0

問題イベント名:CLR20r3
System.ApplicationException
で落ちる。

System.Threading.Mutex.ReleaseMutex
で落ちているようす。

**Comment by hibara** [comment]
ご報告ありがとうございます！

先ほどこの問題を修正した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/
