### ISSUE TITLE
(v.3.2.3.0)パスワード保存設定を行った後、パスワードを変更したときの挙動

### ISSUE THREAD

**Issue by Cotton-Latent** [hibara/AttacheCase3#55]
お世話になります。いつも有難く使わせて頂いております。

件名の通りパスワードの設定に関してバグのように見える現象が
ありましたためご報告させて頂きます。

まず、
「オプション＞動作設定＞一般＞パスワード」から暗号化時のパスワード保存に
パスワードを入力して、「適用＞OK」をクリックします。

次に暗号化の際、
暗号化のパスワード再確認ページで設定されたパスワードが入力された
状態になっていると思います。しかし別のパスワードを使いたい場合もあったりします。

まずこのページで「キャンセル」を押すと、最初のパスワード入力ページに移動します。
それから、パスワードを別のものに変更し「OK」を押してパスワード再確認ページでも
パスワードを変更して「OK」ボタンを押すと暗号化は無事に完了します。

上記の操作を行って暗号化されたファイルは、別のものに変更したパスワードによって
復元出来るものと期待されるのではないかと思います。しかし、そうはならず最初に
オプションで設定されたパスワードで復元出来るような状態になっています。

まずは動作の確認の程、宜しくお願い致します。

**Comment by hibara** [comment]
ご報告いただいたのに、長らく放置してしまい、申し訳ありません。。。

確かにおっしゃるとおりの動作になっています。現状の仕様ですと、記憶パスワードが設定されていると、それが固定され変更できないようになっています。

とはいえ、それが仕様であるならば、キャンセルして入力できるようになっているのもおかしいですし、誤操作の元になりかねません。

ですので基本的に、記憶パスワードが設定されているが、キャンセル操作を行って別のパスワードを入力したときは、そちらのパスワードが優先されるように次版で修正したいと思います。

ではよろしくお願いいたします。

**Comment by hibara** [comment]
先ほどこの問題を修正した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/
