### ISSUE TITLE
(Ver.2.8.4.0)フォルダごと暗号化したファイルの復号に失敗する。

### ISSUE THREAD

**Issue by gotomasao** [hibara/AttacheCase3#56]
いつもご利用させていただいております。
フォルダに複数のファイルを格納して暗号化し、復号した場合に以下のメッセージが表示され、
復号化に失敗します。

[メッセージ]
不正なファイルパスが含まれています。復号化できません。
※Ver.3.3.0.0では再現しませんでした。

**Comment by hibara** [comment]
ご報告ありがとうございます！

最近のバージョンで入った脆弱性対策の影響かもしれません。本日、また新しい ver.2.8.5.0に、不正なファイルパスがあった場合に、エラーメッセージダイアログ表示とともに、そのファイルパスも表示されるようになっています。

お手数ですが、どういったファイルパスが表示されているかご報告いただけるとたいへん助かります。

ちなみにメッセージダイアログ表示中に、Ctrl + Cでメッセージ内容をコピー＆ペーストすることができます。

ではよろしくお願いいたします。

**Comment by gotomasao** [comment]
返信ありがとうございます。
ファイルパスが表示されるメッセージのスクリーンショットを取得しようと思いましたが、
Ver.2.8.5.0にバージョンアップして同様の操作を行いましたが、本現象は発生しなくなりました。
※Ver.2.8.4.0で復号に失敗したファイルを、Ver.2.8.5.0で復号しても再現しませんでした。

上記より、Ver2.8.5.0では本現象は改善されているように思います。

**Comment by hibara** [comment]
いったんこのIssueはクローズします。もし再発した際は再度、ご報告いただけると助かります！
