### ISSUE TITLE
パスワード付ZIPファイルを作成した際、7ZIPで解凍できない（Win10）

### ISSUE THREAD

**Issue by MasaakiFuse** [hibara/AttacheCase3#57]
環境（Win10）
パスワード付ZIP作成ファイルを作成した際、7ZIPで解凍できない（Win10）
環境で、PkzipWeakに設定
ファイルを選択し、パスワード（abcde12345）を設定し、
ファイルを確認しようと7ZIPを使い開くがパスワードエラーとなります。

**Comment by MasaakiFuse** [comment]
パスワード”1”で暗号化したZIP形式ファイルを解凍できない。
Lhplus総当たりパスワード探索をかけたが、数字で探索しても8桁まで探索してヒットする気配がない。

**Comment by hibara** [comment]
ご報告ありがとうございます！

こちらでも同様の条件で圧縮して、7zip、Windowsデフォルトの解凍機能、Lhaplusでも同様に解凍できることを確認いたしました。

もし可能であれば、その解凍不能になるデータを送ってくださるか、どういった条件で起きるかなどをご報告いただけるとたいへん助かります。

よろしくお願いいたします。

**Comment by MasaakiFuse** [comment]
お手数をおかけします。
以下環境です。
[cid:image001.jpg@01D44125.B642BF10]
[cid:image002.jpg@01D44125.B642BF10]
実験条件

(USB)F:ドライブに添付画像を置き
(USB)E:ドライブに圧縮画像を生成(オプションにて指定)
暗号・複合パスワードをそれぞれ”a1”に設定（オプションにて指定）

まず、暗号化ATCアイコンをクリック（キーが黄色に！）
対象ファイルをドラッグ＆ドロップ
暗号化キー確認
Eドライブの生成ファイル（添付ATCファイル：複合できます。）
パスワードZIPアイコンをクリック（キーが黄色に）
暗号化キー確認
Eドライブの生成ファイル（添付ZIPファイル：複合できません。）
7-zipで解凍すると、作成されたホルダの中に、サイズ0の画像ファイルが生成されます。

他になに必要な情報ありましたら、ご連絡いただければ幸いです。
よろしくお願いいたします。

**Comment by MasaakiFuse** [comment]
お手数をおかけします。
本日、以下と同様の確認すると動作するようです。
何かの拍子に、先日のような状態に陥ってしまうようです。
これまで、対応されてきたなかでなにか、心当たらいございますか？

From: Fuse, Masaaki
Sent: Friday, August 31, 2018 12:26 PM
To: hibara/AttacheCase3; hibara/AttacheCase3
Cc: Author
Subject: RE: [hibara/AttacheCase3] パスワード付ZIPファイルを作成した際、7ZIPで解凍できない（Win10） (#57)

お手数をおかけします。
以下環境です。
[cid:image001.jpg@01D443C0.57BF3E80]
[cid:image002.jpg@01D443C0.57BF3E80]
実験条件

(USB)F:ドライブに添付画像を置き
(USB)E:ドライブに圧縮画像を生成(オプションにて指定)
暗号・複合パスワードをそれぞれ”a1”に設定（オプションにて指定）

まず、暗号化ATCアイコンをクリック（キーが黄色に！）
対象ファイルをドラッグ＆ドロップ
暗号化キー確認
Eドライブの生成ファイル（添付ATCファイル：複合できます。）
パスワードZIPアイコンをクリック（キーが黄色に）
暗号化キー確認
Eドライブの生成ファイル（添付ZIPファイル：複合できません。）
7-zipで解凍すると、作成されたホルダの中に、サイズ0の画像ファイルが生成されます。

他になに必要な情報ありましたら、ご連絡いただければ幸いです。
よろしくお願いいたします。

**Comment by hibara** [comment]
特に対応中に心当たりはありません。今回の脆弱性対応は、7-zipに影響を及ぼしておりませんし・・・

添付の画像とありますが、このGitHubから来るメールに対して、添付しておりますでしょうか？　当該の画像ファイルを取得できていません。もし可能であれば、この以下 Issue のスレッドで直接アップロードしていただけるか、

https://github.com/hibara/AttacheCase3/issues/57

m@hibara.org まで直接メールいただけると助かります。

ではよろしくお願いいたします。
