### ISSUE TITLE
Ver2.xで暗号化したファイルをVer3.4.0.0で復号化できない（Win7）

### ISSUE THREAD

**Issue by hmiyauchi8801** [hibara/AttacheCase3#59]
初めまして
アタッシェケースを利用させていただき感謝しております。

さて、Ver3.4.0.0を利用させていただきましたが
既存暗号化（Ver2.7.5.0～Ver2.8.3.0）「.atc」ファイルを復号化したところ
パスワード入力要求に正しく入力した後以下メッセージを表示し終了となり復号化ができませんでした。
「ファイル、またはフォルダーパスが不正です。処理を中止します。」
![atcerr](https://user-images.githubusercontent.com/43019302/45128358-24b20c00-b16d-11e8-80a3-7056a72e8bf6.png)

Ver3.3.0.0では既存暗号化（Ver2.7.5.0～Ver2.8.3.0）「.atc」ファイルの復号化は問題なくできました。

当方環境の問題かもしれませんが、ご確認いただけますと幸いです。

【利用環境】
Windows 7 Professional  6.1.7601　　　64 bit
.NET Framework 2.0 Service Pack 2
　日本語Language Pack（Service Pack 2）
.NET Framework 3.0 Service Pack 2
　日本語Language Pack（Service Pack 2）
.NET Framework 3.5 Service Pack 1 
　日本語Language Pack（Service Pack 1）
.NET Framework 4（フル版）
　日本語Language Pack（フル版）

**Comment by VZMNAPZO** [comment]
Windows10 32bitの私の環境でも同一現象が起きています。Ver3.4.0.0において新規に発生した不具合と思われますので、修正いただければ有難いです。

**Comment by hibara** [comment]
ご報告ありがとうございます！

先ほどこの問題を修正した最新版の方をアップロードさせていただきました。
下記よりご利用くださいませ。

アタッシェケース ver.3.4.1.0
https://hibara.org/software/attachecase/

**Comment by VZMNAPZO** [comment]
修正ありがとうございます。無事、古い暗号化ファイルを復号出来ました。
