### ISSUE TITLE
ディレクトリーエリアが保護されない

### ISSUE THREAD

**Issue by Kamakura-Taro** [hibara/AttacheCase3#6]
お世話になります。

メニュー「オプション」→「動作設定」の項目で、｢保存｣→「暗号化/復号する」について、「常に同じ場所に保存する」フォルダの表示エリアが、「復号する」では変更保護されるのに対し、「暗号化」では変更可能になっています。

**Comment by hibara** [comment]
いろいろとご報告ありがとうございます！（順次対応していきます）

この件ですが、変更保護されるのではなく、逆の、編集が可能になる（背景がホワイトになる）のが正解の仕様です。ですので、そのようにバグ修正をいたしました。よろしくご確認ください。

ver.3.0.1.5
https://hibara.org/software/attachecase/

**Comment by Kamakura-Taro** [comment]
対応をありがとうございます。

首記の件、確認いたしました。
