### ISSUE TITLE
コマンドラインオプションのパスワードについて

### ISSUE THREAD

**Issue by takapon0221** [hibara/AttacheCase3#64]
ver3.4.1.0で、コマンドラインオプションの "/p" を使用し、パスワードを指定していますが
パスワードの文字として "=" (イコール)を使用することができません。

コマンドラインオプションを "=" で分解しているので、パスワード中の "=" も分解されているようです。

また、"/nohide" の指定もうまく動きません。
(画面で参照しているオプションが nohide ではなく、 notmask のようです)

お手すきの際にでも、修正頂ければと思います。

よろしくお願いします。

**Comment by hibara** [comment]
> ver3.4.1.0で、コマンドラインオプションの "/p" を使用し、パスワードを指定していますが
パスワードの文字として "=" (イコール)を使用することができません。

現在公開されている最新バージョン（vwe.3.5.0.0）では正常に動いているようです。今後は最新版でのご確認をお願いできますでしょうか。

> また、"/nohide" の指定もうまく動きません。
> (画面で参照しているオプションが nohide ではなく、 notmask のようです)

https://hibara.org/software/attachecase/help/howto/#command-line-option

そのとおりです。まず「/nomask」というコマンドラインオプションは存在しません。仕様となります。オプション名が紛らわしいのはたしかですが、わりと歴史のあるソフトなのでこのように適当な名前になっているものもあります（すみません）。ちなみに今のところ、バックグラウンドで動かすオプションは存在しません。
