### ISSUE TITLE
IMEがONにならず困ってます。

### ISSUE THREAD

**Issue by ghost** [hibara/AttacheCase3#66]
AttacheCaseには、長い間お世話になっております。

暗号化する時に、IMEがONにならず困ってます。
（「パスワード文字列を隠さず入力する」にチェックを入れても入れなくても）

何も入力せずに「確認入力」ではOKです。
そして、←で戻ると、今度はOK（入力できます）。
手間がかかりますが、何とか使っています。

当方の環境は、Windows10(64bit)、AttacheCase#3(Ver3.5.0.0)です。

**Comment by hibara** [comment]
新たにパスワード入力のテキストボックスのIMEを常にONするオプションを追加しました。「動作設定」→「ウィンドウ」→「パスワード入力用のすべてのテキストボックスでIMEをオンにする」にチェックを入れてください（デフォルトではOFFになっています）。

新バージョン、ver.3.5.2.0から実装されています。よろしければ以下からお試しください。
https://hibara.org/software/attachecase/

ではよろしくお願いいたします。
