### ISSUE TITLE
Ver.3.5.1.0 で1回目のパスワード入力が伏字にならない

### ISSUE THREAD

**Issue by yukicon2** [hibara/AttacheCase3#68]
Ver.3.5.1.0 で1回目のパスワード入力がそのまま表示される。
2度目（再確認）の入力時はマスクされて伏字になる。

**Comment by hibara** [comment]
ご報告ありがとうございます。修正しました。

具体的な原因と修正内容ですが、パスワードを入力するテキストボックスのプロパティの一部がいつの間にか「Multiline=True」となっていたことが原因のようです。削除することで正常にパスワードがマスクされるようになったようです。

https://github.com/hibara/AttacheCase3/commit/d7796acddc20ddbed6f94c517a27c3d2e57234af#diff-92c2875594e5df1eef26bbb77687008aL1816-L1818

なお、新バージョンのver.3.5.2.0で修正されています。以下からよろしければお試しください。
https://hibara.org/software/attachecase/

よろしくお願いいたします。
