### ISSUE TITLE
アタッシェケースでテキストファイルを暗号化するとエラーになる。

### ISSUE THREAD

**Issue by HiraYoo** [hibara/AttacheCase3#69]
アタッシェケース#3 Version3.5.1.0 をダウンロードし、動作検証しています。

Windows10 Pro 64Bit Memory 8GB

テキストファイルを暗号化するとエラーが発生します。
エラーは発生するものの、暗号化は完了しています。
画像ファイル、Office文書は問題なく暗号化できます。
テキストファイルは秀丸で作成しています。

〇エラー内容
アプリケーションのコンポーネントで、ハンドルされていない例外が発生しました。
[続行]をクリックすると、アプリケーションはこのエラーを無視し、続行しようとします。
[終了]をクリックすると、アプリケーションは直ちに終了します。

'10416' の値は'Value'に対して有効ではありません。"Value"は'minimum'と'maximum'の
間でなければいけません。
パラメータ名:Value

パラメーター名:Value
   場所 System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   場所 AttacheCase.Form1.backgroundWorker_ProgressChanged(Object sender, ProgressChangedEventArgs e)
   場所 System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)

Googleで検索しても同様のエラーは見つかりません。
何が考えられるでしょうか？

よろしくお願いいたします。

**Comment by hibara** [comment]
連絡が遅くなって申し訳ありません。もし可能であればエラーが発生する該当のテキストファイルをいただくことは可能でしょうか？（可能なら、 <m@hibara.org>までお願いします）

エラーメッセージを見る限り、暗号化処理に関係なく、プログレスバー表示（進捗表示）の値に不正な値（0〜100%外）が入ってしまってエラーが起きてしまっているようです。

**Comment by hibara** [comment]
別のユーザーさんがこのIssueを目にしていただいたようで、再現性のあるファイルをメールで送っていただきました。ここに添付したテキストファイルを暗号化しようとすると、たしかにプログレスバー表示での例外が発生するようです。
[検証結果.txt](https://github.com/hibara/AttacheCase3/files/4346124/default.txt)

この再現性により、バグ原因が特定され、修正することができました。

具体的な原因と修正ですが、[FileEncryptクラス](https://github.com/hibara/AttacheCase3/blob/master/AttacheCase/FileEncypt3.cs)にあるプログレスバーの合計値を入れる変数「TotalFileSize」が、コンストラクタで「-1」と初期化され、結果的に暗号化前に計算するファイルの合計値が若干小さくなってしまっていたようです。

とはいえ、誤差は1byteなので、大きなサイズのものではこの不具合は発生せず、比較的小さなサイズのファイルを暗号化するときに発生していたようです。

よって、コンストラクタの初期化時に「0」とすることで正常にプログレスバーが表示されることを確認いたしました。

https://github.com/hibara/AttacheCase3/commit/208aff244710cb6776b64b323862ce2030e6851c#diff-bc7c11dc6f6730d9e482cc2a771c0febL147

新しいバージョンである、ver.3.5.2.0でこの不具合は修正されていますので、もしよろしければ以下からお試しください。

https://hibara.org/software/attachecase/

ではよろしくお願いいたします。
