### ISSUE TITLE
暗号化ファイル名の書式設定をしても、空白のファイル名になる

### ISSUE THREAD

**Issue by Kamakura-Taro** [hibara/AttacheCase3#7]
メニュー「オプション」→「動作設定」の項目で、｢保存｣→「暗号化」で「暗号化ファイル名の書式設定」にもチェックを書式として「file」としてチェックすると、ファイル名が空白の暗号化ファイルが生成されます。

**Comment by hibara** [comment]
誠に申し訳ありません、、、こちらのご報告への返信を見逃しておりました。

ver.3.1.0.2の段階で修正を入れて、すでに今のバージョンで問題なく動作しているはずです。以下からダウンロードができます。

ver.3.1.0.9
https://hibara.org/software/attachecase/

よろしくお願いいたします。
