### ISSUE TITLE
Ver.3.5.2.0 で /list による暗号処理ができない

### ISSUE THREAD

**Issue by yukicon2** [hibara/AttacheCase3#70]
コマンドライン　オプションが以下の時に
 /exit=1 /ow=1 /en=1 /oneby=1 /withext=1 /del=0 /list=List.txt

List.txt の内容
a.txt ← このファイルのみが処理され、エラーとなる
b.txt
c.txt

最初の1つを暗号化するとエラーとなり
「予期せぬエラーが発生しました。処理を中止します。」

**Comment by hibara** [comment]
ご報告ありがとうございます。
"/list"単体だと問題なく動作するようです。おそらく他に指定されたコマンドラインオプションとの組み合わせで問題が起こっているような気がします。次版までに原因を究明し修正いたします。

**Comment by hibara** [comment]
該当箇所を調べて見たところ、コマンドラインオプションの「/list」というよりも、「/oneby=1」に問題があり、むしろ動作設定の「保存」->「暗号化」->「複数ファイルの場合：フォルダー内のファイルを一つずつ暗号化」を選択した状態で暗号化を行うと「予期せぬエラーが発生しました。処理を中止します。」のエラーメッセージが表示されることが分かりました。

具体的には「一つずつ暗号化」する際の処理の途中で、正しく暗号化オブジェクトが初期化されていない箇所があり、連続で処理する際に、二番目で必ずエラーになってしまう問題のようでした。

新バージョンではすでにこの問題に対処し、公開しています。その他、細かいバグなども併せて修正されています。よろしければ以下からダウンロードしてお試しください。

アタッシェケース#3　ver.3.5.3.0 
https://hibara.org/software/attachecase/

または、

https://github.com/hibara/AttacheCase3/releases

からダウンロードしてお試しください。
