### ISSUE TITLE
「暗号化ファイル名に拡張子を含める」ときの拡張子展開

### ISSUE THREAD

**Issue by uzr-th** [hibara/AttacheCase3#71]
version 3.5.3.0 です。「動作設定」＞「暗号化」＞「暗号化ファイル名に拡張子を含める」をONにすると、拡張子部分が常に「atc」に展開されるようです。
* 暗号化ファイル名を自動で設定「&lt;filename&gt;_&lt;date:yyyy_MM_dd&gt;&lt;ext&gt;」
* 暗号化対象ファイル名「aaa.jpg」
* 期待している暗号化ファイル名「aaa.jpg_2020_05_30.atc」
* 実際に出力される暗号化ファイル名「aaa.atc_2020_05_30.atc」

**Comment by hibara** [comment]
ご報告ありがとうございます。上記の条件で試したところ、現象は再現されませんでした（きちんと、jpgとなるところは正しいファイル名「aaa.jpg_2020_06_06.atc」というようになりました）。

他にこの現象が再現する条件などはございますでしょうか？　もしあれば教えていただけるとありがたいです。よろしくお願いいたします。
