### ISSUE TITLE
複合化できない

### ISSUE THREAD

**Issue by MightyATOM164** [hibara/AttacheCase3#73]
お世話になります。
アタッシュケース#3 Version3.5.4.0にて複合化できなくなりました。
エラーは「パスワードが違うか、ファイルが破損している可能性があります。複合できませんでした。」です。
同じ環境で使用しており、暗号化後にアプリのVersion変更などしていません。
どうすればよろしいでしょうか？

**Comment by hibara** [comment]
> 「パスワードが違うか、ファイルが破損している可能性があります。複合できませんでした。」

多く寄せられる事象ですが、このエラーメッセージが表示されている場合は、ほぼ「メッセージ通り」のことが起きているのだと思います。

可能性としては、パスワードがちがうことが多いです。今一度ご確認ください。アタッシェケースでは、暗号化ファイルにパスワードを含めるなど危ない仕様にはなっていないので、復号できなかったとき、ファイルが破損したか、パスワードがちがうのかを判断することができません。

ですので、内部的はパスワードを元に復号してみたが、成功したとき中から読み出せるはずのトークン（文字列）が読み出せなかった、ということから先のメッセージ表示となっています。

ではよろしくお願いいたします。
