### ISSUE TITLE
Can not get rid of ini reading comfirm dialog box

### ISSUE THREAD

**Issue by Riajyuu** [hibara/AttacheCase3#74]
![image](https://user-images.githubusercontent.com/16912240/162866933-2eb60675-3a65-4fc4-acc7-f63f495b087f.png)

This checkbox simply doesn't work.

The red text above that seems not aligning properly too.

Here is my ini file

[_AtcCase.zip](https://github.com/hibara/AttacheCase3/files/8469025/_AtcCase.zip)

**Comment by hibara** [comment]
Thanks for the issue. 
I have fixed that bug.

The version up is here.    
[https://github.com/hibara/AttacheCase3/releases](https://github.com/hibara/AttacheCase3/releases)
