### ISSUE TITLE
Deletion Checkbox doesn't Match that in ini File

### ISSUE THREAD

**Issue by Riajyuu** [hibara/AttacheCase3#75]
Here is the preferences:
![image](https://user-images.githubusercontent.com/16912240/164131053-106d6182-f91b-4358-93e8-88771213b762.png)

In the first encrypt form, it is correct:
![image](https://user-images.githubusercontent.com/16912240/164131209-5ef3d740-df9e-4a33-b4d7-83e3340b08c1.png)

But in the password confirm form and decryption form, it doesn't look right:
![image](https://user-images.githubusercontent.com/16912240/164131334-98b8f3fe-c8f6-4570-98af-9850cc702825.png)
![image](https://user-images.githubusercontent.com/16912240/164131461-30d50b0a-5a53-49d5-9458-1c0d3eca40a3.png)

But the deletion operations are properly performed.

Here is my ini file
[_AtcCase.zip](https://github.com/hibara/AttacheCase3/files/8517612/_AtcCase.zip)

**Comment by hibara** [comment]
Fixed. I think it will be working as expected.
[https://github.com/hibara/AttacheCase3/releases](https://github.com/hibara/AttacheCase3/releases)
