### ISSUE TITLE
パスワードとしてファイルを指定する機能で、エラーメッセージ表示

### ISSUE THREAD

**Issue by Kamakura-Taro** [hibara/AttacheCase3#8]
お世話になります。

パスワードとしてファイルを指定する機能で、暗号化はできても(正しく暗号化されているかは不明)、復号化でエラーメッセージが出ます。同じ操作をVer 2.8.2.8で行うと暗号化・復号化ができます(パスワードの事前登録による暗号化・復号化も含めて)。

また、Ver 3では復号時のパスワードとしてのファイル登録をすると、暗号時のファイル登録エリアに表示されます(復号時のエリアは表示なし)。

**Comment by hibara** [comment]
パスワード周りの設定はこんがらがっておりまして・・・ご不便をおかけして申し訳ありません。

とはいえ、大きく修正を入れて、正常に動作するように対処・対応したつもりです。以下新版のアタッシェケースでお試し下さい。

ver.3.0.1.6
https://hibara.org/software/attachecase/

**Comment by Kamakura-Taro** [comment]
対応をありがとうございました。

確認しました。
