### ISSUE TITLE
復号化 すると、元のファイルのタイムスタンプが現在に変わっている

### ISSUE THREAD

**Issue by yukicon** [hibara/AttacheCase3#9]
Ver.3.0.1.3 にて
暗号化 → 復号化 すると、元のファイルのタイムスタンプが現在に変わっている。

以下の設定はチェックしていません。
動作設定 → 保存 → 暗号化
　オリジナルのファイルとフォルダーのタイムスタンプを保持する

ご確認ください。

**Comment by hibara** [comment]
ご報告ありがとうございます！

まさにご指摘のとおり、復号時に異常値が入ってしまい（内部的にはエラー）→現在日時が設定されるということになっていたようです。

正しく暗号化ファイル内にある日時を取得して設定するように改良しました。

ver.3.0.1.5
https://hibara.org/software/attachecase/

よろしければお試しいただければと思います。
では今後ともよろしくお願いいたします。

**Comment by yukicon** [comment]
修正されていることを確認いたしました。
